/* -*- Mode: IDL; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* vim: set sw=2 :miv */
/*
//
// BEGIN SONGBIRD GPL
//
// This file is part of the Songbird web player.
//
// Copyright(c) 2005-2008 POTI, Inc.
// http://songbirdnest.com
//
// This file may be licensed under the terms of of the
// GNU General Public License Version 2 (the "GPL").
//
// Software distributed under the License is distributed
// on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either
// express or implied. See the GPL for the specific language
// governing rights and limitations.
//
// You should have received a copy of the GPL along with this
// program. If not, go to http://www.gnu.org/licenses/gpl.html
// or write to the Free Software Foundation, Inc.,
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
//
// END SONGBIRD GPL
//
*/

#include "nsISupports.idl"

/**
 * \interface sbITemporaryFileService
 *
 *   The sbITemporaryFileService interface provides support for creating
 * temporary files and directories.  These files and directories are deleted
 * when the application quits.
 *
 * "@songbirdnest.com/Songbird/TemporaryFileService;1"
 * Use get service with this component.
 */

interface nsIFile;

[scriptable, uuid(838c57f5-c2d7-445a-8a16-bc70c57eec9e)]
interface sbITemporaryFileService : nsISupports
{
  /**
   * \brief Root directory of temporary files and directories.
   */

  readonly attribute nsIFile rootTemporaryDirectory;


  /**
   * \brief Create and return a new and unique temporary file of the type
   *        specified by aType.  If aBaseName is specified, use aBaseName as the
   *        base name of the file.  If aExtension is specified, use aExtension
   *        as the file extension.
   *
   * \param aType               Type of file to create.  One of nsIFile file
   *                            types.
   * \param aBaseName           Optional file base name.
   * \param aExtension          Optional file extension.
   */

  nsIFile createFile(in unsigned long            aType,
                     [optional] in AString       aBaseName,
                     [optional] in AString       aExtension);
};


//
// C++ defs.
//

%{C++
#define SB_TEMPORARYFILESERVICE_CONTRACTID \
          "@songbirdnest.com/Songbird/TemporaryFileService;1"
%}C++

