/*
//
// BEGIN SONGBIRD GPL
// 
// This file is part of the Songbird web player.
//
// Copyright© 2006 POTI, Inc.
// http://songbirdnest.com
// 
// This file may be licensed under the terms of of the
// GNU General Public License Version 2 (the “GPL”).
// 
// Software distributed under the License is distributed 
// on an “AS IS” basis, WITHOUT WARRANTY OF ANY KIND, either 
// express or implied. See the GPL for the specific language 
// governing rights and limitations.
//
// You should have received a copy of the GPL along with this 
// program. If not, go to http://www.gnu.org/licenses/gpl.html
// or write to the Free Software Foundation, Inc., 
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
// 
// END SONGBIRD GPL
//
 */
#include "nsISupports.idl"

[scriptable, uuid(6AFCACC5-9D63-499d-B8D0-B40C66859818)]
interface sbIGlobalHotkeyCallback : nsISupports
{
  void OnHotkey( in wstring key_id );
};

[scriptable, uuid(284E14BF-5CE4-4434-A733-4379D27D799E)]
interface sbIGlobalHotkeys : nsISupports
{
  void AddHotkey( in PRInt32 keyCode, in PRBool altKey, in PRBool ctrlKey, in PRBool shiftKey, in PRBool metaKey, in wstring key_id, in sbIGlobalHotkeyCallback cb );
  void RemoveHotkey( in wstring key_id );
  void RemoveAllHotkeys();
};

