/*
//
// BEGIN SONGBIRD GPL
// 
// This file is part of the Songbird web player.
//
// Copyright© 2006 Pioneers of the Inevitable LLC
// http://songbirdnest.com
// 
// This file may be licensed under the terms of of the
// GNU General Public License Version 2 (the “GPL”).
// 
// Software distributed under the License is distributed 
// on an “AS IS” basis, WITHOUT WARRANTY OF ANY KIND, either 
// express or implied. See the GPL for the specific language 
// governing rights and limitations.
//
// You should have received a copy of the GPL along with this 
// program. If not, go to http://www.gnu.org/licenses/gpl.html
// or write to the Free Software Foundation, Inc., 
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
// 
// END SONGBIRD GPL
//
 */
#include "nsISupports.idl"

//{ 0x10eb215d, 0xd70a, 0x4eee, { 0xb5, 0xce, 0x39, 0x99, 0xb, 0x16, 0x70, 0x6c } };
[scriptable, uuid(10EB215D-D70A-4eee-B5CE-39990B16706C)]
interface sbIWindowMinMaxCallback : nsISupports
{
  PRInt32 GetMinWidth( );
  PRInt32 GetMinHeight( );
  PRInt32 GetMaxWidth( );
  PRInt32 GetMaxHeight( );
  void OnWindowClose( );
};

[scriptable, uuid(5F4ABE1E-76D2-43b5-8D5E-E6E272A49C50)]
interface sbIWindowMinMax : nsISupports
{
  void SetCallback( in nsISupports window, in sbIWindowMinMaxCallback cb );
  void ResetCallback( in nsISupports window );
};

