#!/bin/bash

APPNAME="Songbird.app"
TARGET="${2}/${APPNAME}"
RESDIR="${TARGET}/Contents/Resources"
if [ -z "${DISTHELPER_DISTINI}" ] ; then
  DISTHELPER_DISTINI="${RESDIR}/songbird.ini"
fi

cd "${RESDIR}"
exec ./disthelper install
