/*
//
// BEGIN NIGHTINGALE GPL
// 
// This file is part of the Nightingale web player.
//
// Copyright© 2005-2008 POTI, Inc.
// http://getnightingale.com
// 
// This file may be licensed under the terms of of the
// GNU General Public License Version 2 (the "GPL").
// 
// Software distributed under the License is distributed 
// on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either 
// express or implied. See the GPL for the specific language 
// governing rights and limitations.
//
// You should have received a copy of the GPL along with this 
// program. If not, go to http://www.gnu.org/licenses/gpl.html
// or write to the Free Software Foundation, Inc., 
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
// 
// END NIGHTINGALE GPL
//
*/

/**
 * \file sbIDeviceStatus.idl
 */

#include "nsISupports.idl"

interface sbIMediaItem;
interface sbIMediaList;

/**
 * \interface sbIDeviceStatus
 * \note Implementations of this interface must be threadsafe.
 *
 * Holds the current status of a device, idle, syncing, etc with all the
 * relevent information.
 */
[scriptable, uuid(c4b8e380-1dd1-11b2-b549-be35d52daa54)]
interface sbIDeviceStatus: nsISupports {
  /**
   * \brief The current overall state of the device.
   * \sa sbIDevice::STATE_*
  */
  attribute unsigned long currentState;

  /**
   * \brief The current sub state of the device, copying could be a sub state
   *        of the syncing state.
   * \sa sbIDevice::STATE_*
  */
  attribute unsigned long currentSubState;

  /**
   * Sets the state message
   */
  attribute AString stateMessage;

  /**
   * Sets the current operation
   */
  attribute AString currentOperation;

  /**
   * Sets the current progress as a percent. Done is 1.0.
   */
  attribute double progress;

  /**
   * Sets the current work item # for example processing multiple files
   */
  attribute PRInt64 workItemProgress;

  /**
   * Sets the current work item type
   */
  attribute PRInt32 workItemType;

  /**
   * Sets the end count for processing multiple items
   */
  attribute PRInt64 workItemProgressEndCount;

  /**
   * Current Item being processed
   */
  attribute sbIMediaItem mediaItem;
  
  /**
   * These are for showing an estimated time of completion for an operation,
   * like copying, transcoding, etc. Generally it will be for a single item
   * operation, like copying a file to the device.
   */
  
  /**
   * \brief The time elapsed in milliseconds since currentState was last at STATE_IDLE
   */
  readonly attribute PRUint32 elapsedTime;

  /**
   * Current List being processed
   */
  attribute sbIMediaList mediaList;

  /**
   * A new batch has begun since you last checked
   */
  attribute boolean isNewBatch;
  
  /**
   * \brief Initialize the DeviceStatus component for a device
   */
  void init(in AString aDeviceID);
};
