/*
 *=BEGIN SONGBIRD GPL
 *
 * This file is part of the Songbird web player.
 *
 * Copyright(c) 2005-2011 POTI, Inc.
 * http://www.songbirdnest.com
 *
 * This file may be licensed under the terms of of the
 * GNU General Public License Version 2 (the ``GPL'').
 *
 * Software distributed under the License is distributed
 * on an ``AS IS'' basis, WITHOUT WARRANTY OF ANY KIND, either
 * express or implied. See the GPL for the specific language
 * governing rights and limitations.
 *
 * You should have received a copy of the GPL along with this
 * program. If not, go to http://www.gnu.org/licenses/gpl.html
 * or write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 *=END SONGBIRD GPL
 */
 
#include "nsISupports.idl"

interface sbILibrary;
interface sbILibraryChangeset;
interface sbIMediaList;
interface nsIArray;
 
[scriptable, uuid(f26d3ef1-3d94-4c3e-a5b9-26a29cf92f03)]
interface sbIDeviceLibrarySyncDiff : nsISupports
{
  // These two are mutually exclusive
  const unsigned long SYNC_FLAG_EXPORT_ALL = 1<<0;
  const unsigned long SYNC_FLAG_EXPORT_PLAYLISTS = 1<<1;

  const unsigned long SYNC_FLAG_IMPORT = 1<<2;

  // We might add others here later (e.g. still images) - but not for now.
  const unsigned long SYNC_TYPE_AUDIO = 1<<0;
  const unsigned long SYNC_TYPE_VIDEO = 1<<1;
  
  /**
   * Generate lists of items to sync in 2-way sync.
   *
   * \param aMode            The configured sync mode. Combination of
   *                         SYNC_FLAG_* constants.
   * \param aPlaylistMatchingUsesOriginGUID
   *                         Whether a matching playlist is found based on
   *                         the originItemGUID property (if true), or a name
   *                         match (if false)
   * \param aMediaTypes      The media types (bit mask) to generate sync lists
   *                         for. One or more of the SYNC_TYPE_* constants.
   * \param aSourceLibrary   The source library for the sync operation - usually
   *                         the main library.
   * \param aDestLibrary     The destination library for the sync operation -
   *                         usually a device library
   * \param aSourceLists     Array of playlists to sync to the destination
   *                         library, used only if SYNC_FLAGS_EXPORT_PLAYLISTS
   *                         is set.
   * \param aExportChangeset The changeset describing items to be exported to
   *                         the destination (device) library.
   *                         This will be non-null if SYNC_FLAG_EXPORT_ALL or
   *                         SYNC_FLAG_EXPORT_PLAYLISTS is passed (though the
   *                         changeset may still be empty in that case!)
   *                         In this list, an ADDED item should be added to the
   *                         destination library, and the corresponding file
   *                         copied (or transcoded) to the target.
   *                         A MODIFIED item should be modified in the target
   *                         library (the target item will be given in the
   *                         sbILibraryChange), and the target file overwritten.
   * \param aImportChangeset The changeset describing items to be imported to
   *                         the source (main) library.
   *                         This will be non-null if SYNC_FLAG_IMPORT is
   *                         passed (though the changeset may still be empty)
   *                         Here, an ADDED item should be added to the source
   *                         (main) library. A MODIFIED item will, likewise,
   *                         modify an existing item 
   *                         (sbILibraryChange::destinationItem), but note that
   *                         this MUST only ever occur for lists. Thus, there is
   *                         no actual target file to overwrite.
   *                         It would be an internal error for an
   *                         sbILibraryChange in this list to have
   *                         operation == MODIFIED, and isList false.
   */
  void generateSyncLists(in unsigned long aMode,
                         in boolean aPlaylistMatchingUsesOriginGUID,
                         in unsigned long aMediaTypes,
                         in sbILibrary aSourceLibrary,
                         in sbILibrary aDestLibrary,
                         in nsIArray   aSourceLists,
                         out sbILibraryChangeset aExportChangeset,
                         out sbILibraryChangeset aImportChangeset);

  /**
   * Generate change set to apply to or from a device library during
   * drag-and-drop operation. 
   *
   * \param aPlaylistMatchingUsesOriginGUID
   *                         Whether a matching playlist is found based on
   *                         the originItemGUID property (if true), or a name
   *                         match (if false)
   * \param aSourceLibrary   The source library for the drop operation.
   * \param aDestLibrary     The destination library for the drop operation.
   * \param aSourceList      A source playlist being copied to the destination
   *                         library. May be null if aSourceItems is not.
   * \param aSourceItems     An array of sbIMediaItems for the drop operation.
   *                         May be null if aSourceList is not.
   * \param aChangeset       The changes to apply to the destination library
   *                         as a result of this drop operation.
   */
  void generateDropLists(in boolean aPlaylistMatchingUsesOriginGUID,
                         in sbILibrary aSourceLibrary,
                         in sbILibrary aDestLibrary,
                         in sbIMediaList aSourceList,
                         in nsIArray     aSourceItems,
                         out sbILibraryChangeset aChangeset);
};

%{C++
#define SONGBIRD_DEVICELIBRARYSYNCDIFF_DESCRIPTION      \
  "Songbird Device Sync Diff Generator"
#define SONGBIRD_DEVICELIBRARYSYNCDIFF_CONTRACTID       \
  "@songbirdnest.com/Songbird/Device/DeviceLibrarySyncDiff;1"
#define SONGBIRD_DEVICELIBRARYSYNCDIFF_CLASSNAME        \
  "Songbird Device Sync Diff"
#define SONGBIRD_DEVICELIBRARYSYNCDIFF_CID              \
{ /* e5060de5-9fa9-4cad-b7db-4c42243d9c6f */            \
  0xe5060de5,                                           \
  0x9fa9,                                               \
  0x4cad,                                               \
  {0xb7, 0xdb, 0x4c, 0x42, 0x24, 0x3d, 0x9c, 0x6f}      \
}
%}

  
