/*
//
// BEGIN SONGBIRD GPL
// 
// This file is part of the Songbird web player.
//
// Copyright© 2005-2008 POTI, Inc.
// http://songbirdnest.com
// 
// This file may be licensed under the terms of of the
// GNU General Public License Version 2 (the "GPL").
// 
// Software distributed under the License is distributed 
// on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either 
// express or implied. See the GPL for the specific language 
// governing rights and limitations.
//
// You should have received a copy of the GPL along with this 
// program. If not, go to http://www.gnu.org/licenses/gpl.html
// or write to the Free Software Foundation, Inc., 
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
// 
// END SONGBIRD GPL
//
*/

#include "nsISupports.idl"

interface sbIDeviceEvent;
interface sbIDeviceEventListener;

/**
 * \interface sbIDeviceEventTarget
 * \brief [UNIMPLEMENTED UNTIL AFTER 0.3]
 * \note Implementations of this interface must be threadsafe.
 */
[scriptable, uuid(c83fad0a-d0f7-4b66-9596-b6a3cfa21d65)]
interface sbIDeviceEventTarget : nsISupports
{
  /**
   * 
   */
  void dispatchEvent(in sbIDeviceEvent aEvent);

  /**
   * 
   */
  void addEventListener(in sbIDeviceEventListener aListener);

  /**
   * 
   */
  void removeEventListener(in sbIDeviceEventListener aListener);
};
