/*
 *=BEGIN NIGHTINGALE GPL
 *
 * This file is part of the Nightingale web player.
 *
 * Copyright(c) 2005-2009 POTI, Inc.
 * http://www.getnightingale.com
 *
 * This file may be licensed under the terms of of the
 * GNU General Public License Version 2 (the ``GPL'').
 *
 * Software distributed under the License is distributed
 * on an ``AS IS'' basis, WITHOUT WARRANTY OF ANY KIND, either
 * express or implied. See the GPL for the specific language
 * governing rights and limitations.
 *
 * You should have received a copy of the GPL along with this
 * program. If not, go to http://www.gnu.org/licenses/gpl.html
 * or write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 *=END NIGHTINGALE GPL
 */

/**
 * \file sbIDeviceCapsCompatibility.idl
 * \brief Interface for the device capabilities comparison service
 */

#include "nsISupports.idl"

interface sbIDeviceCapabilities;
interface sbIMediaFormat;

/**
 * \interface sbIDeviceCapsCompatibility
 * \brief This service determines if a media file is compatible with a
 *        particular device.
 */
[scriptable, uuid(82bf1267-7a96-4f83-97b6-32faa64f3325)]
interface sbIDeviceCapsCompatibility : nsISupports
{
  /**
   * \brief Initializes the device capabilities, media format and media
   *        content type of the form sbIDeviceCapabilities::CONTENT_*.
   * \param aDeviceVideoFormat Device video format from the device capabilities.
   * \param aMediaFormat Media format from media inspector.
   * \param aContentType Content type of form sbIDeviceCapabilities::CONTENT_*
   *        for the media item to transfer.
   */
  void initialize(in sbIDeviceCapabilities aDeviceCapabilities,
                  in sbIMediaFormat aMediaFormat,
                  in unsigned long aContentType);

  /**
   * \brief Compare the media file format with device capabilities to
   *        determine whether they are compatible.
   *
   * \returns true if compatible.
   */
  boolean compare();
};

%{C++
#define NIGHTINGALE_DEVICECAPSCOMPATIBILITY_DESCRIPTION      \
  "Nightingale Device Capabilities Compatibility Component"
#define NIGHTINGALE_DEVICECAPSCOMPATIBILITY_CONTRACTID       \
  "@getnightingale.com/Nightingale/Device/DeviceCapsCompatibility;1"
#define NIGHTINGALE_DEVICECAPSCOMPATIBILITY_CLASSNAME        \
  "Nightingale Device Capabilities"
#define NIGHTINGALE_DEVICECAPSCOMPATIBILITY_CID              \
{ /* e8717123-1bb2-4ca5-a442-7e8424fbdb49 */              \
  0xe8717123,                                             \
  0x1bb2,                                                 \
  0x4ca5,                                                 \
  {0xa4, 0x42, 0x7e, 0x84, 0x24, 0xfb, 0xdb, 0x49}        \
}
%}
