/*
//
// BEGIN SONGBIRD GPL
// 
// This file is part of the Songbird web player.
//
// Copyright© 2005-2008 POTI, Inc.
// http://songbirdnest.com
// 
// This file may be licensed under the terms of of the
// GNU General Public License Version 2 (the “GPL”).
// 
// Software distributed under the License is distributed 
// on an “AS IS” basis, WITHOUT WARRANTY OF ANY KIND, either 
// express or implied. See the GPL for the specific language 
// governing rights and limitations.
//
// You should have received a copy of the GPL along with this 
// program. If not, go to http://www.gnu.org/licenses/gpl.html
// or write to the Free Software Foundation, Inc., 
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
// 
// END SONGBIRD GPL
//
*/

#include "nsISupports.idl"

interface sbIDeviceEvent;

/**
 * \interface sbIDeviceEventListener
 * \brief [UNIMPLEMENTED UNTIL AFTER 0.3]
 *
 * Used to listen to events on a particular device, controller, etc.
 */
[scriptable, uuid(a8c5b212-2b04-497e-978a-56493f1f2dda)]
interface sbIDeviceEventListener : nsISupports
{
  /**
   * aEvent - information about the event
   */
  void onDeviceEvent(in sbIDeviceEvent aEvent);
};
