#include "nsISupports.idl"

interface sbIMashTapeUtils;
interface sbIMashTapeCallback;
interface nsISimpleEnumerator;

[scriptable, function, uuid(a1b678c0-64a3-11dd-ad8b-0800200c9a66)]
interface sbIMashTapeProvider : nsISupports
{
	readonly attribute string providerName;
	readonly attribute string providerType;
	void query(in AUTF8String searchTerms, in sbIMashTapeCallback updateFn);
};

[scriptable, function, uuid(65f60210-73bc-11dd-ad8b-0800200c9a66)]
interface sbIMashTapeInfoProvider : sbIMashTapeProvider
{
	readonly attribute long numSections;
	readonly attribute string providerIconBio;
	readonly attribute string providerIconTags;
	readonly attribute string providerIconDiscography;
	readonly attribute string providerIconMembers;
	readonly attribute string providerIconLinks;
};

[scriptable, function, uuid(8da914c0-64a6-11dd-ad8b-0800200c9a66)]
interface sbIMashTapePhotoProvider : sbIMashTapeProvider
{
	readonly attribute string providerIcon;
};

[scriptable, function, uuid(a414db50-64c8-11dd-ad8b-0800200c9a66)]
interface sbIMashTapeFlashProvider : sbIMashTapeProvider
{
	readonly attribute string providerIcon;
};

[scriptable, function, uuid(c8925af0-b4e8-11dd-ad8b-0800200c9a66)]
interface sbIMashTapeRSSProvider : sbIMashTapeProvider
{
	readonly attribute string providerIcon;
};

[scriptable, function, uuid(097ef180-b12a-11dd-ad8b-0800200c9a66)]
interface sbIMashTapeReviewProvider : sbIMashTapeProvider
{
	readonly attribute string providerIcon;
	void queryFull(in AUTF8String artist, in AUTF8String album,
			in AUTF8String track, in sbIMashTapeCallback updateFn);
};

[scriptable, function, uuid(8cb80ab0-b129-11dd-ad8b-0800200c9a66)]
interface sbIMashTapeTabProvider : sbIMashTapeProvider
{
	readonly attribute string tabName;
};

/*******************************/

[scriptable, function, uuid(959b2c40-68ca-11dd-ad8b-0800200c9a66)]
interface sbIMashTapeCallback : nsISupports
{
};

[scriptable, uuid(10ADB8E6-4A7D-4789-ACDA-B0975E6F137D)]
interface sbIMashTapePhoto : nsISupports
{
	readonly attribute string imageUrl;
	readonly attribute string imageTitle;
	readonly attribute string authorName;
	readonly attribute string authorUrl;
	readonly attribute unsigned long timestamp;
};

[scriptable, uuid(7373b260-c584-11dd-ad8b-0800200c9a66)]
interface sbIMashTapeListener : nsISupports
{
	/* section == "photo" || "bio"
	   for "photo", data will be the URL to the image
	   for "bio", data will be the full HTML-formatted text of the bio
	*/
	void onInfoUpdated(in AUTF8String section, in AUTF8String data);
	void onPhotosUpdated([array, size_is(photoCount)]
		in sbIMashTapePhoto photos, in unsigned long photoCount);
};

[scriptable, function, uuid(7E991583-030F-4945-8273-A34A5B2752CF)]
interface sbIMashTapeManager : nsISupports
{
	void addListener(in sbIMashTapeListener aListener);
	void removeListener(in sbIMashTapeListener aListener);
	
	void updateInfo(in AUTF8String section, in AUTF8String data);
	void updatePhotos([array, size_is(photoCount)]
		in sbIMashTapePhoto photos, in unsigned long photoCount);
};

