#preedTODO: add copyright
DEPTH = ../../..
topsrcdir = /media/disk/Linux/makepkg/songbird
srcdir = /media/disk/Linux/makepkg/songbird/extensions/mashTape/components
VPATH = /media/disk/Linux/makepkg/songbird/extensions/mashTape/components

include $(DEPTH)/build/autodefs.mk

IS_EXTENSION = 1

include $(topsrcdir)/build/rules.mk
