#preedTODO: add copyright
DEPTH = ../../../..
topsrcdir = /media/disk/Linux/makepkg/songbird
srcdir = /media/disk/Linux/makepkg/songbird/extensions/mashTape/components/src
VPATH = /media/disk/Linux/makepkg/songbird/extensions/mashTape/components/src

include $(DEPTH)/build/autodefs.mk

IS_EXTENSION = 1

SONGBIRD_COMPONENTS = $(srcdir)/Flickr.js \
                      $(srcdir)/GoogleBlogs.js \
                      $(srcdir)/HypeM.js \
                      $(srcdir)/Info.js \
                      $(srcdir)/SmugMug.js \
                      $(srcdir)/Wikipedia.js \
                      $(srcdir)/YouTube.js \
                      $(srcdir)/mashTapeManager.js \
                      $(NULL)

include $(topsrcdir)/build/rules.mk

