/*
//
// BEGIN SONGBIRD GPL
// 
// This file is part of the Songbird web player.
//
// Copyright© 2005-2008 POTI, Inc.
// http://songbirdnest.com
// 
// This file may be licensed under the terms of of the
// GNU General Public License Version 2 (the "GPL").
// 
// Software distributed under the License is distributed 
// on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either 
// express or implied. See the GPL for the specific language 
// governing rights and limitations.
//
// You should have received a copy of the GPL along with this 
// program. If not, go to http://www.gnu.org/licenses/gpl.html
// or write to the Free Software Foundation, Inc., 
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
// 
// END SONGBIRD GPL
//
*/

/**
 * \file sbIDevice.idl
 * \brief [UNIMPLEMENTED UNTIL AFTER 0.3]
 */

#include "nsISupports.idl"

interface nsIPropertyBag2;
interface nsIVariant;

interface sbIDeviceCapabilities;
interface sbIDeviceContent;
interface sbIDeviceProperties;
interface sbIDeviceParameters;

/**
 * \interface sbIDevice
 * \note Implementations of this interface must be threadsafe.
 *
 * The main interface to all device objects
 */
[scriptable, uuid(98fcf422-d1e7-47fc-bd6f-9027d8c4952a)]
interface sbIDevice : nsISupports
{
  /**
   * A human-readable name identifying the device. Optional.
   */
  readonly attribute AString name;

  /**
   * The id of the controller that created the device.
   */
  readonly attribute nsIDPtr controllerId;
  
  /**
   * The id of the device
   */
  readonly attribute nsIDPtr id;

  /**
   * Called when the device should initialize.
   */
  void connect();

  /**
   * Called when the device is to finalize.
   */
  void disconnect();

  /**
   * Whether or not the device is currently connected.
   */
  readonly attribute boolean connected;

  /**
   * Whether or not the device's events are being processed in additional threads
   * (i.e. off the main UI thread).
   */
  readonly attribute boolean threaded;

  /**
   * Get a preference stored on the device.
   */
  nsIVariant getPreference(in AString aPrefName);

  /**
   * Sets a preference stored on the device.
   */
  void setPreference(in AString aPrefName,
                     in nsIVariant aPrefValue);

  /**
   * Get the capabilities of the device.
   */
  readonly attribute sbIDeviceCapabilities capabilities;

  /**
   * All the device's content.
   */
  readonly attribute sbIDeviceContent content;

  /**
   * The parameters with which the device was created
   */
  readonly attribute nsIPropertyBag2 parameters;
  
  /**
   * The device's properties.
   */
  readonly attribute sbIDeviceProperties properties;
  
  /**
   * Whether the device is currently performing a busy operation, like copying
   * or deleting. This is defined by the device as to what states determine the
   * device is busy.
   */
  readonly attribute boolean isBusy;
  
  /**
   * Whether it is safe to disconnect the device, generally this is when it
   * is not performing a critical operation like copying a file to/from the
   * device. This is also defined by the device as to what states determine the
   * device can be disconnected. Usefull for when the user wants to shutdown
   * the application.
   */
  readonly attribute boolean canDisconnect;
  
  /**
   * Whether the device is busy, idle, syncing, mounting, etc.
   * @see sbIDeviceEvent::EVENT_DEVICE_MEDIA_READ_*
   * @see sbIDeviceEvent::EVENT_DEVICE_MEDIA_WRITE_*
   * @see STATE_*
   */
  readonly attribute unsigned long state;

  const unsigned long STATE_IDLE            = 0;  // Not doing anything
  const unsigned long STATE_SYNCING         = 1;  // Performing a sync
  // These are not related to syncing (used for manual mode)
  const unsigned long STATE_COPYING         = 2;  // Copying a single file
  const unsigned long STATE_DELETING        = 3;  // Deleting a single file
  const unsigned long STATE_UPDATING        = 4;  // Updating a single file
  const unsigned long STATE_MOUNTING        = 5;  // (un)Mounting the device
  const unsigned long STATE_DOWNLOADING     = 6;
  const unsigned long STATE_UPLOADING       = 7;
  const unsigned long STATE_DOWNLOAD_PAUSED = 8;
  const unsigned long STATE_UPLOAD_PAUSED   = 9;
  const unsigned long STATE_DISCONNECTED    = 10; // Device is disconnected


  const unsigned long REQUEST_FLAG_USER  = 0x80000000;
  const unsigned long REQUEST_FLAG_WRITE = 0x40000000;

  /* read requests */
  const unsigned long REQUEST_MOUNT     = 1;
  const unsigned long REQUEST_READ      = 2;
  const unsigned long REQUEST_EJECT     = 3;
  const unsigned long REQUEST_SUSPEND   = 4;

  /* write requests */
  const unsigned long REQUEST_WRITE         = REQUEST_FLAG_WRITE + 1;
  const unsigned long REQUEST_DELETE        = REQUEST_FLAG_WRITE + 2;
  const unsigned long REQUEST_SYNC          = REQUEST_FLAG_WRITE + 3;
  /* delete all files on the device */
  const unsigned long REQUEST_WIPE          = REQUEST_FLAG_WRITE + 4;
  /* move an item inside one playlist */
  const unsigned long REQUEST_MOVE          = REQUEST_FLAG_WRITE + 5;
  const unsigned long REQUEST_UPDATE        = REQUEST_FLAG_WRITE + 6;
  const unsigned long REQUEST_NEW_PLAYLIST  = REQUEST_FLAG_WRITE + 7;

  /**
   * 
   */
  void submitRequest(in unsigned long aRequest, in nsIPropertyBag2 aRequestParameters);
  /**
   * Cancel all current pending requests
   */
  void cancelRequests();

  /**
   * Eject device.
   */
  void eject();
};
