/* vim: set sw=2 :*/
/*
//
// BEGIN NIGHTINGALE GPL
//
// This file is part of the Nightingale web player.
//
// Copyright(c) 2005-2009 POTI, Inc.
// http://getnightingale.com
//
// This file may be licensed under the terms of of the
// GNU General Public License Version 2 (the "GPL").
//
// Software distributed under the License is distributed
// on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either
// express or implied. See the GPL for the specific language
// governing rights and limitations.
//
// You should have received a copy of the GPL along with this
// program. If not, go to http://www.gnu.org/licenses/gpl.html
// or write to the Free Software Foundation, Inc.,
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
//
// END NIGHTINGALE GPL
//
*/

#include "nsISupports.idl"

interface sbILibrary;
interface nsIURI;

[scriptable, uuid(5e4e170f-7052-4f2b-910d-cafc1f35d4c9)]
interface sbIMediaManagementService : nsISupports
{
  /**
   * the library being managed by the media management service
   */
  readonly attribute sbILibrary managedLibrary;
  
  /**
   * whether the media management service is enabled
   */
  attribute boolean isEnabled;
  
  /**
   * whether the media management service is currently actively scanning
   * the managed library
   */
  readonly attribute boolean isScanning;

  /**
   * Runs the management job to make sure that all items in the
   * media list are located and organized under the media library folder. 
   * TODO: possibly implement later if at all
   */
  //sbIJobProgress consolidateList(in sbIMediaList aMediaList);
  /**
   * Returns the managed folder URI
   */
   readonly attribute nsIURI managedFolder;
};

//
// C++ defs.
//

%{C++
#define SB_MEDIAMANAGEMENTSERVICE_CONTRACTID \
  "@getnightingale.com/Nightingale/media-manager-service;1"
%}C++
