/*
//
// BEGIN NIGHTINGALE GPL
//
// This file is part of the Nightingale web player.
//
// Copyright(c) 2005-2009 POTI, Inc.
// http://getnightingale.com
//
// This file may be licensed under the terms of of the
// GNU General Public License Version 2 (the "GPL").
//
// Software distributed under the License is distributed
// on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either
// express or implied. See the GPL for the specific language
// governing rights and limitations.
//
// You should have received a copy of the GPL along with this
// program. If not, go to http://www.gnu.org/licenses/gpl.html
// or write to the Free Software Foundation, Inc.,
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
//
// END NIGHTINGALE GPL
//
*/

/**
 * \file sbIMediaManagementJob.idl
 * \brief Definition of the sbIMediaManagementJob interface
 */

#include "nsISupports.idl"
#include "sbIJobProgress.idl"

interface sbIMediaList;
interface nsIPropertyBag2;

[scriptable, uuid(a018846a-1dd1-11b2-851e-d362304f7007)]
interface sbIMediaManagementJob : sbIJobProgress
{
  /**
   * Initialze the media management job by preparing to act upon a particular
   * media list
   * \param aMediaList the media list to organize
   * \param aProperties properties for the job; \see sbIMediaFileManager
   * \throw NS_SUCCESS_LOSS_OF_INSIGNIFICANT_DATA if there are no items
   * \see sIMediaFileManager::init
   */
  void init(in sbIMediaList aMediaList,
            [optional] in nsIPropertyBag2 aProperties);

  /**
   * This will scan the list and organize the files based on the preferences,
   * only if the file is already located in the media library folder.
   * \see init();
   */
  void organizeMediaList();
};

//
// C++ defs.
//

%{C++
#define SB_MEDIAMANAGEMENTJOB_CONTRACTID \
          "@getnightingale.com/Nightingale/media-manager/job;1"
%}C++
