/*
//
// BEGIN SONGBIRD GPL
//
// This file is part of the Songbird web player.
//
// Copyright(c) 2005-2009 POTI, Inc.
// http://songbirdnest.com
//
// This file may be licensed under the terms of of the
// GNU General Public License Version 2 (the "GPL").
//
// Software distributed under the License is distributed
// on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either
// express or implied. See the GPL for the specific language
// governing rights and limitations.
//
// You should have received a copy of the GPL along with this
// program. If not, go to http://www.gnu.org/licenses/gpl.html
// or write to the Free Software Foundation, Inc.,
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
//
// END SONGBIRD GPL
//
*/

/**
 * \file sbIMediaManagementJob.idl
 * \brief Definition of the sbIMediaManagementJob interface
 */

#include "nsISupports.idl"
#include "sbIJobProgress.idl"

interface sbIMediaList;
interface nsILocalFile;

[scriptable, uuid(20fa9550-1dd2-11b2-8f5d-9215396171cf)]
interface sbIMediaManagementJob : sbIJobProgress
{
  /**
   * Initialze the media management job by preparing to act upon a particular
   * media list
   * \param aMediaList the media list to organize
   * \param aMediaFolder the folder to organize things in;
   *                     if not specified, use the value from prefs
   * \throw NS_SUCCESS_LOSS_OF_INSIGNIFICANT_DATA if there are no items
   */
  void init(in sbIMediaList aMediaList, [optional] in nsILocalFile aMediaFolder);

  /**
   * This will scan the list and organize the files based on the preferences,
   * only if the file is already located in the media library folder.
   * \see init();
   */
  void organizeMediaList();
};

//
// C++ defs.
//

%{C++
#define SB_MEDIAMANAGEMENTJOB_CONTRACTID \
          "@songbirdnest.com/Songbird/media-manager/job;1"
%}C++
