/*
//
// BEGIN SONGBIRD GPL
// 
// This file is part of the Songbird web player.
//
// Copyright(c) 2005-2007 POTI, Inc.
// http://songbirdnest.com
// 
// This file may be licensed under the terms of of the
// GNU General Public License Version 2 (the "GPL").
// 
// Software distributed under the License is distributed 
// on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either 
// express or implied. See the GPL for the specific language 
// governing rights and limitations.
//
// You should have received a copy of the GPL along with this 
// program. If not, go to http://www.gnu.org/licenses/gpl.html
// or write to the Free Software Foundation, Inc., 
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
// 
// END SONGBIRD GPL
//
 */

/**
 * \file sbIPlaylistWidget.idl
 * \brief Definition of the sbIPlaylistWidget interface
 * \sa
 */

#include "nsISupports.idl"

interface sbIMediaListView;
interface sbIPlaylistCommands;
interface sbIPropertyInfo;

/**
 * \interface sbIPlaylistWidget
 * \brief 
 */
[scriptable, uuid(7a33d37c-34a3-4fe0-8d8d-5eb6e680457a)]
interface sbIPlaylistWidget : nsISupports
{
  void rescanCommands();
  sbIMediaListView getListView();
  void bind( in sbIMediaListView mediaListView,
             in sbIPlaylistCommands commands,
             in boolean resize,
             in boolean collapse );
  void showColumn( in AString aColumnName );
  void hideColumn( in AString aColumnName );
  void moveColumnBefore( in AString aColumnName,
                         in AString aBeforeColumnName );
  void insertColumn( in sbIPropertyInfo aPropInfo,
                     in boolean aIsHidden,
                     in long aWidth,
                     in AString aSortOrder,
                     in AString aBeforeCol );
};

