/*
//
// BEGIN SONGBIRD GPL
// 
// This file is part of the Songbird web player.
//
// Copyright© 2006 POTI, Inc.
// http://songbirdnest.com
// 
// This file may be licensed under the terms of of the
// GNU General Public License Version 2 (the “GPL”).
// 
// Software distributed under the License is distributed 
// on an “AS IS” basis, WITHOUT WARRANTY OF ANY KIND, either 
// express or implied. See the GPL for the specific language 
// governing rights and limitations.
//
// You should have received a copy of the GPL along with this 
// program. If not, go to http://www.gnu.org/licenses/gpl.html
// or write to the Free Software Foundation, Inc., 
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
// 
// END SONGBIRD GPL
//
 */

#include "nsISupports.idl"
#include "nsIObserver.idl"
/**
 * The sbIDataRemote Interface
 */
[scriptable, uuid(79eece3f-d661-4f03-83dd-5764a0f77088)]
interface sbIDataRemote : nsIObserver
{
  /**
   * Sets internal state, must be called before any other methods
   */
  void init(in wstring key, in wstring root);

  /**
   * 
   */
  void unbind();

  /**
   * 
   */
  void bindEventFunction(in wstring func);

  /**
   * 
   */
  void bindCallbackFunction(in wstring func,
                            in boolean suppressFirst);

  /**
   * 
   */
  void bindCallbackProperty(in wstring obj, // This needs to be a DOM element.  Can this even work?
                            in wstring prop,
                            in boolean is_bool,
                            in boolean is_not,
                            in wstring eval);
 
  /**
   * 
   */
  void bindCallbackAttribute(in wstring obj, // This needs to be a DOM element.
                             in wstring prop,
                             in boolean is_bool,
                             in boolean is_not,
                             in wstring eval);

  /**
   * 
   */
  void setValue(in wstring value);

  /**
   * DOH!  int can translate okay, but bool becomes "true"
   */
  void setBoolValue(in boolean value);

  /**
   * 
   */
  wstring getValue();

  /**
   * 
   */
  long getIntValue();

  /**
   * 
   */
  boolean getBoolValue();

  /**
   * 
   */
  long makeIntValue(in wstring value);
};