#preedTODO: add copyright
DEPTH = ../../..
topsrcdir = /media/disk/Linux/makepkg/songbird
srcdir = /media/disk/Linux/makepkg/songbird/extensions/mashTape/defaults
VPATH = /media/disk/Linux/makepkg/songbird/extensions/mashTape/defaults

include $(DEPTH)/build/autodefs.mk

IS_EXTENSION = 1

SUBDIRS = preferences \
          $(NULL)

include $(topsrcdir)/build/rules.mk
