/* -*- Mode: IDL; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* vim: set sw=2 :miv */
/*
//
// BEGIN SONGBIRD GPL
//
// This file is part of the Songbird web player.
//
// Copyright(c) 2005-2008 POTI, Inc.
// http://songbirdnest.com
//
// This file may be licensed under the terms of of the
// GNU General Public License Version 2 (the "GPL").
//
// Software distributed under the License is distributed
// on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either
// express or implied. See the GPL for the specific language
// governing rights and limitations.
//
// You should have received a copy of the GPL along with this
// program. If not, go to http://www.gnu.org/licenses/gpl.html
// or write to the Free Software Foundation, Inc.,
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
//
// END SONGBIRD GPL
//
*/

//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
//
// Interface description for the album art fetcher set interface.
//
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------

#include "nsISupports.idl"
#include "sbIAlbumArtFetcher.idl"


/**
 * \interface sbIAlbumArtFetcherSet
 * \brief Interface for an album art fetcher set.  Instantiate as a component
 *        instance.
 *
 *   An album art fetcher set may be used to fetch album art from multiple
 * sources.  This interface will obtain an ordered set of album art fetchers and
 * call each fetcher in succession until one successfully fetches album art.
 *
 * \sa sbIAlbumArtFetcher
 */

[scriptable, uuid(f6f030ba-1dd1-11b2-8764-ad0493676ed0)]
interface sbIAlbumArtFetcherSet : sbIAlbumArtFetcher
{
  const unsigned long TYPE_ALL              = 0x00;
  const unsigned long TYPE_REMOTE           = 0x01;
  const unsigned long TYPE_LOCAL            = 0x02;

  /**
   * \brief Type of fetchers in the set (local, remote, both)
   */
  attribute unsigned long fetcherType;
};


//
// C++ defs.
//

%{C++
#define SB_ALBUMARTFETCHERSET_CONTRACTID \
          "@songbirdnest.com/Songbird/album-art-fetcher-set;1"
%}C++

