#preedTODO: add copyright
DEPTH = ../../../..
topsrcdir = /media/disk/Linux/makepkg/songbird
srcdir = /media/disk/Linux/makepkg/songbird/extensions/mashTape/defaults/preferences
VPATH = /media/disk/Linux/makepkg/songbird/extensions/mashTape/defaults/preferences

include $(DEPTH)/build/autodefs.mk

IS_EXTENSION = 1

SONGBIRD_PREFS += $(srcdir)/prefs.js \
                  $(NULL)

include $(topsrcdir)/build/rules.mk
