#!/bin/sh

/root/make-code-tarball.sh /var/www/sites/developer.getnightingale.com/nightly/snapshots

/root/make-dependencies-tarball.sh /var/www/sites/developer.getnightingale.com/nightly/dependency_snapshots

