/*
 *=BEGIN SONGBIRD GPL
 *
 * This file is part of the Songbird web player.
 *
 * Copyright(c) 2005-2010 POTI, Inc.
 * http://www.songbirdnest.com
 *
 * This file may be licensed under the terms of of the
 * GNU General Public License Version 2 (the ``GPL'').
 *
 * Software distributed under the License is distributed
 * on an ``AS IS'' basis, WITHOUT WARRANTY OF ANY KIND, either
 * express or implied. See the GPL for the specific language
 * governing rights and limitations.
 *
 * You should have received a copy of the GPL along with this
 * program. If not, go to http://www.gnu.org/licenses/gpl.html
 * or write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 *=END SONGBIRD GPL
 */

#include "nsISupports.idl"

interface nsIStringEnumerator;

[scriptable, uuid(937f3e19-f9ef-4d7c-9afa-7e388338954e)]
interface sbIMediacoreCapabilities : nsISupports
{
  /**
   * \brief Audio file extensions (eg. mp3, aac, m4a, ...)
   */
  readonly attribute nsIStringEnumerator audioExtensions;
  /**
   * \brief Video file extensions (eg. avi, mpg, mov, ...)
   */
  readonly attribute nsIStringEnumerator videoExtensions;
  /**
   * \brief Image file extensions (eg. jpg, tiff, png, ...)
   */
  readonly attribute nsIStringEnumerator imageExtensions;

  // XXXAus: Encoders? Formats supported FourCC? MIME Type? I have no idea.
  //         We'll figure out what to do for that stuff when we get to 
  //         encoding/transcoding

  /**
   * \brief Supports audio playback?
   */
  readonly attribute boolean supportsAudioPlayback;
  /**
   * \brief Supports video playback?
   */
  readonly attribute boolean supportsVideoPlayback;
  /**
   * \brief Supports image playback?
   */
  readonly attribute boolean supportsImagePlayback;

  /**
   * \brief Supports transcoding audio?
   */
  readonly attribute boolean supportsAudioTranscode;
  /**
   * \brief Supports transcoding video?
   */
  readonly attribute boolean supportsVideoTranscode;
  /**
   * \brief Supports transcoding images?
   */
  readonly attribute boolean supportsImageTranscode;

};

%{C++

#define SB_MEDIACORE_CAPABILITIES_DESCRIPTION    \
  "Songbird Mediacore Capabilities"
#define SB_MEDIACORE_CAPABILITIES_CONTRACTID     \
  "@songbirdnest.com/Songbird/Mediacore/Capabilities;1"
#define SB_MEDIACORE_CAPABILITIES_CLASSNAME      \
  "sbMediacoreCapabilities"
#define SB_MEDIACORE_CAPABILITIES_CID            \
  { 0x938bbc3d, 0x5c03, 0x4744, { 0xac, 0x2f, 0x20, 0x22, 0xbd, 0xdb, 0x2, 0x19 } }
  
%}
