/*
 //
// BEGIN SONGBIRD GPL
// 
// This file is part of the Songbird web player.
//
// Copyright(c) 2005-2008 POTI, Inc.
// http://songbirdnest.com
// 
// This file may be licensed under the terms of of the
// GNU General Public License Version 2 (the "GPL").
// 
// Software distributed under the License is distributed 
// on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either 
// express or implied. See the GPL for the specific language 
// governing rights and limitations.
//
// You should have received a copy of the GPL along with this 
// program. If not, go to http://www.gnu.org/licenses/gpl.html
// or write to the Free Software Foundation, Inc., 
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
// 
// END SONGBIRD GPL
//
 */

#include "nsISupports.idl"

[scriptable, uuid(ef15b3dd-bccc-4e1b-8c4d-3ef8d63bfd0d)]
interface sbIMediacoreError : nsISupports
{
  const unsigned long UNINITIALIZED                   = 0;
  // A general error which doesn't fit in any other category.
  const unsigned long FAILED                          = 1;

  // General file access errors, reading, writing, etc.
  
  // Source file was not found.
  const unsigned long SB_RESOURCE_NOT_FOUND               = 10;
  // Unable to read from or write to a RESOURCE.
  const unsigned long SB_RESOURCE_READ                    = 11;
  const unsigned long SB_RESOURCE_WRITE                   = 12;
  // Unable to open a RESOURCE in read, write or both modes.
  const unsigned long SB_RESOURCE_OPEN_READ               = 13;
  const unsigned long SB_RESOURCE_OPEN_WRITE              = 14;
  const unsigned long SB_RESOURCE_OPEN_READ_WRITE         = 15;
  // Unable to close the RESOURCE.
  const unsigned long SB_RESOURCE_CLOSE                   = 16;
  // Unable to seek in the RESOURCE (could be truncated)
  const unsigned long SB_RESOURCE_SEEK                    = 17;
  // Unable to write to destination due to no space left.
  const unsigned long SB_RESOURCE_NO_SPACE_LEFT           = 18;

  // Errors with the actual stream contents, decoders, encoders, etc.
  
  // Unable to determine the type of the media
  const unsigned long SB_STREAM_TYPE_NOT_FOUND         = 51;
  // We do not handle this type of media 
  const unsigned long SB_STREAM_WRONG_TYPE             = 52;
  // We do not have a codec to decode/encode this media.
  const unsigned long SB_STREAM_CODEC_NOT_FOUND        = 53;
  // Unable to decode the media.
  const unsigned long SB_STREAM_DECODE                 = 54;
  // Unable to encode the media.
  const unsigned long SB_STREAM_ENCODE                 = 55;
  // The media is DRM protected.
  const unsigned long SB_STREAM_DRM_PROTECTED          = 56;
  // Other failures
  const unsigned long SB_STREAM_FAILURE                = 57;

  /**
   * \brief Error code.
   */
  readonly attribute unsigned long code;

  /**
   * \brief Error message (human readable string, localized, preferably).
   */
  readonly attribute AString message;
};
