/*
 //
// BEGIN SONGBIRD GPL
// 
// This file is part of the Songbird web player.
//
// Copyright(c) 2005-2008 POTI, Inc.
// http://songbirdnest.com
// 
// This file may be licensed under the terms of of the
// GNU General Public License Version 2 (the "GPL").
// 
// Software distributed under the License is distributed 
// on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either 
// express or implied. See the GPL for the specific language 
// governing rights and limitations.
//
// You should have received a copy of the GPL along with this 
// program. If not, go to http://www.gnu.org/licenses/gpl.html
// or write to the Free Software Foundation, Inc., 
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
// 
// END SONGBIRD GPL
//
 */

#include "nsISupports.idl"

interface nsIArray;

interface sbIMediacoreSequence;
interface sbIMediacoreSequenceGenerator;
interface sbIMediaListView;

[scriptable, uuid(91e8edfc-17a8-47af-8d75-1bbe9ab5fa5f)]
interface sbIMediacoreSequencer : nsISupports
{
  const unsigned long MODE_FORWARD    = 0;
  const unsigned long MODE_REVERSE    = 1;
  const unsigned long MODE_SHUFFLE    = 1 << 1;

  const unsigned long MODE_CUSTOM     = 1 << 16;

  attribute unsigned long mode;

  const unsigned long MODE_REPEAT_NONE = 0;
  const unsigned long MODE_REPEAT_ONE = 1;
  const unsigned long MODE_REPEAT_ALL = 1 << 1;

  attribute unsigned long repeatMode;

  attribute sbIMediaListView view;

  readonly attribute nsIArray currentSequence;
  attribute unsigned long sequencePosition;

  void play();
  void next();
  void previous();

  // When in custom mode, this generator is used to generate the sequence.
  attribute sbIMediacoreSequenceGenerator customGenerator;
};
