/*
 //
// BEGIN SONGBIRD GPL
// 
// This file is part of the Songbird web player.
//
// Copyright(c) 2005-2008 POTI, Inc.
// http://songbirdnest.com
// 
// This file may be licensed under the terms of of the
// GNU General Public License Version 2 (the "GPL").
// 
// Software distributed under the License is distributed 
// on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either 
// express or implied. See the GPL for the specific language 
// governing rights and limitations.
//
// You should have received a copy of the GPL along with this 
// program. If not, go to http://www.gnu.org/licenses/gpl.html
// or write to the Free Software Foundation, Inc., 
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
// 
// END SONGBIRD GPL
//
 */

#include "nsISupports.idl"

interface nsIVariant;

interface sbIMediacore;
interface sbIMediacoreError;
interface sbIMediacoreEventTarget;

[scriptable, uuid(801dcd5b-2443-4757-adc2-5be282103539)]
interface sbIMediacoreEvent : nsISupports
{
  const unsigned long UNINTIALIZED    = 0x00000000;

  /**
   * \brief Metadata describing current item has changed
   * \note data is an sbIPropertyArray object.
   */
  const unsigned long METADATA_CHANGE = 0x00001000;
  /**
   * \brief URI used for operation has changed
   * \note data is an nsIURI object.
   */
  const unsigned long URI_CHANGE      = 0x00001001;
  /**
   * \brief Current duration has changed
   * \note data is the new duration as an unsigned long long (in milliseconds).
   */
  const unsigned long DURATION_CHANGE = 0x00001002;
  /**
   * \brief Volume has changed
   * \note data is the new volume as a double (from 0 to 1).
   */
  const unsigned long VOLUME_CHANGE   = 0x00001003;
  /**
   * \brief Mute status has changed
   * \note data is the new mute state (boolean, true = muted).
   */
  const unsigned long MUTE_CHANGE     = 0x00001004;

  // Sequencer Events

  /**
   * \brief Before the track playing is changed.
   * \note This event should only be fired by the sequencer.
   * \note data is the new sbIMediaItem that will be played.
   */
  const unsigned long BEFORE_TRACK_CHANGE = 0x00001500;
  /**
   * \brief Track playing has changed.
   * \note This event should only be fired by the sequencer.
   * \note data is the new sbIMediaItem being played.
   */
  const unsigned long TRACK_CHANGE        = 0x00001501;
  /**
   * \brief Index in view of item currently playing has changed.
   * \note This event should only be fired by the sequencer.
   * \note data is the new index (unsigned long).
   */
  const unsigned long TRACK_INDEX_CHANGE  = 0x00001502;
  /**
   *  \brief Sequencer view is about to change
   */
  const unsigned long BEFORE_VIEW_CHANGE  = 0x00001503;
  /**
   * \brief Sequencer view changed.
   */
  const unsigned long VIEW_CHANGE         = 0x00001504;

  // End Sequencer Events

  /**
   * \brief Stream found.
   */
  const unsigned long STREAM_FOUND    = 0x00002000;
  
  /**
   * \brief Buffering.
   * \note data is the buffering progress as a double (from 0 to 1).
   */
  const unsigned long BUFFERING       = 0x00003000;
  /**
   * \brief Buffer underrun, operation is likely to halt.
   */
  const unsigned long BUFFER_UNDERRUN = 0x00003001;
  
  /**
   * \brief Stream has started.
   */
  const unsigned long STREAM_START    = 0x00004000;
  /**
   * \brief Stream is now paused.
   */
  const unsigned long STREAM_PAUSE    = 0x00004001;
  /**
   * \brief End of stream.
   */
  const unsigned long STREAM_END      = 0x00004002;
  /**
   * \brief Stream was stopped.
   */
  const unsigned long STREAM_STOP     = 0x00004003;

  /**
   * \brief Plugin missing for requested format.
   */
  const unsigned long PLUGIN_MISSING  = 0x00008000;

  /**
   * \brief Custom event base value.
   */
  const unsigned long CUSTOM_EVENT_BASE = 0x40000000;

  /**
   * \brief Indicates the event is an error and will have it's error member set.
   */
  const unsigned long ERROR_EVENT       = 0;

  /**
   * \brief The event type.
   */
  readonly attribute unsigned long type;
  /**
   * \brief Error member is only set when type of event is set to ERROR.
   */
  readonly attribute sbIMediacoreError error;

  /**
   * \brief The event data. Payload varies per event type.
   */
  readonly attribute nsIVariant data;

  /**
   * \brief Mediacore that generated the event.
   */
  readonly attribute sbIMediacore origin;
  /**
   * \brief Event Target that dispatched the event.
   */
  readonly attribute sbIMediacoreEventTarget target;
};
