/*
 *=BEGIN SONGBIRD GPL
 *
 * This file is part of the Songbird web player.
 *
 * Copyright(c) 2005-2009 POTI, Inc.
 * http://www.songbirdnest.com
 *
 * This file may be licensed under the terms of of the
 * GNU General Public License Version 2 (the ``GPL'').
 *
 * Software distributed under the License is distributed
 * on an ``AS IS'' basis, WITHOUT WARRANTY OF ANY KIND, either
 * express or implied. See the GPL for the specific language
 * governing rights and limitations.
 *
 * You should have received a copy of the GPL along with this
 * program. If not, go to http://www.gnu.org/licenses/gpl.html
 * or write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 *=END SONGBIRD GPL
 */

#include "nsISupports.idl"


//==============================================================================
//
// @interface sbIOSDControlService
// @brief This interface provides on-screen-display controls for video
//        playback. This service also provides hiding and showing options
//        for the OSD controls.
//
//==============================================================================

[scriptable, uuid(6AE76963-92E6-4A70-9964-F545181E31FE)]
interface sbIOSDControlService : nsISupports
{
  //
  // @brief Inform the OSD service that a video window is opening. This method
  //        should be called whenever a video window opens in order to display
  //        OSD controls for the service.
  // @param aVideoWindow The video window that is opening.
  //
  void onVideoWindowOpened(in nsISupports aVideoWindow);

  //
  // @brief Inform the OSD service that a video window is closing. If this
  //        method is not invoked when a window closes, the OSD controls will
  //        remain open.
  //
  void onVideoWindowWillClose();

  //
  // @brief Inform the OSD service that the main video window has resized.
  //
  void onVideoWindowResized();

  //
  // @brief Inform the OSD service that the main video window has gone into
  //        fullscreen mode.
  //
  void onVideoWindowFullscreenChanged(in boolean aFullscreen);

  //
  // @brief Constants for transitions when hiding or showing the OSD controls.
  //
  const unsigned long TRANSITION_NONE = 0;
  const unsigned long TRANSITION_FADE = 1;

  //
  // @brief Hides the OSD controls from showing on top of the video window.
  // @param aTransitionType A transition option for hiding the controls.
  //
  void hideOSDControls([optional] in unsigned long aTransitionType);

  //
  // @brief Show the OSD controls on top of the video window.
  // @param aTransitionType A transition option for showing the controls.
  //
  void showOSDControls([optional] in unsigned long aTransitionType);
};

