/* -*- Mode: IDL; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* vim: set sw=2 :miv */
/*
//
// BEGIN NIGHTINGALE GPL
//
// This file is part of the Nightingale web player.
//
// Copyright(c) 2005-2008 POTI, Inc.
// http://getnightingale.com
//
// This file may be licensed under the terms of of the
// GNU General Public License Version 2 (the "GPL").
//
// Software distributed under the License is distributed
// on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either
// express or implied. See the GPL for the specific language
// governing rights and limitations.
//
// You should have received a copy of the GPL along with this
// program. If not, go to http://www.gnu.org/licenses/gpl.html
// or write to the Free Software Foundation, Inc.,
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
//
// END NIGHTINGALE GPL
//
*/

#include "nsISupports.idl"

interface nsIDOMDocument;
interface nsIPropertyBag;

[scriptable, function, uuid(6c6bf386-5e02-4f05-8bff-3edeae9750a5)]
interface sbILastFmWebServicesResponse : nsISupports {
  /**
   * \brief ResonseRecievied - An API response has been recieved from Last.FM.
   *
   * \param aSucceeded          Indicates if the call was succesful or not.
   * \param aResponse           Contains the XML response - for successful calls
   *                            and for calls that return an API error See the
   *                            Last.fm API documentation for the DOM structures
   *                            to expect.
   */
  void responseReceived(in boolean aSucceeded, in nsIDOMDocument aResponse);
};

[scriptable, uuid(4ac919d7-7fe1-44ed-8190-5da7fb407691)]
interface sbILastFmWebServices : nsISupports {
  /**
   * \brief ApiCall - Make an API call against the new Last.fm API
   *                  See <http://www.last.fm/api/rest> for the list of API
   *                  calls that are available.
   *
   * \param aMethod             The method name.
   * \param aArguments          A property bag of arguments using key,value.
   *                            This can also be a simple hash object:
   *                              var args = { name: value, name2: value2 };
   * \param aCallback           The callback to inform when complete, this
   *                            can either be the sbILastFmWebServicesResponse
   *                            or a function that resembles the
   *                            responseReceived function in
   *                            sbILastFmWebServicesResponse.
   *
   * \notes Authentication, API keys and request signing will be taken care of
   *        automatically. So there is no need to include them in the arguments.
   *        The values in the aArguments nsIPropertyBag must be strings as they
   *        will be passed as paramaters in the URI or POST call.
   *        Currently this does not work for write calls as we do not log in.
   */
  void apiCall(in string aMethod,
               in nsIPropertyBag aArguments,
               in sbILastFmWebServicesResponse aCallback);
};
