/*
//
// BEGIN SONGBIRD GPL
//
// This file is part of the Songbird web player.
//
// Copyright(c) 2005-2007 POTI, Inc.
// http://songbirdnest.com
//
// This file may be licensed under the terms of of the
// GNU General Public License Version 2 (the "GPL").
//
// Software distributed under the License is distributed
// on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either
// express or implied. See the GPL for the specific language
// governing rights and limitations.
//
// You should have received a copy of the GPL along with this
// program. If not, go to http://www.gnu.org/licenses/gpl.html
// or write to the Free Software Foundation, Inc.,
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
//
// END SONGBIRD GPL
//
*/

/**
 * \file  sbIPropertyArray.idl
 * \brief Definition of the sbIPropertyArray interface
 */

#include "nsIArray.idl"
#include "nsIMutableArray.idl"

[scriptable, uuid(89915b4b-f252-4f45-8351-fd8560363b89)]
interface sbIProperty : nsISupports
{
  /**
   * Get the name of the property.
   */
  readonly attribute AString name;

  /**
   * Get the value of the property.
   */
  readonly attribute AString value;
};

/**
 * \interface sbIPropertyArray
 * \brief An interface to carry around arrays of nsIProperty instances.  Users
 *        of this interface should only QI it to a sbIMutablePropertyArray if
 *        they are the owners of the instance.
 */
[scriptable, uuid(cc75d9ac-cb61-4f6d-afda-1cba8a090b6f)]
interface sbIPropertyArray : nsIArray
{
  /**
   * Gets the property at the specified index
   *
   * \param aIndex The index of the property to retrieve
   */                      
  sbIProperty getPropertyAt(in unsigned long aIndex);

  /**
   * Gets the value for a property in the array
   *
   * \param aName Name of the property to get the value for
   * \return Value of the property
   * \throws NS_ERROR_NOT_AVAILABLE if the property is not in the array
   */
  AString getPropertyValue(in AString aName);

  /**
   * Return the contents of the property array as a string
   */                      
  AString toString();
};

/**
 * \interface sbIPropertyArray
 * \brief An interface to carry around arrays of nsIProperty instances
 */
[scriptable, uuid(9c7f33c9-2283-4404-96a8-07d8b39c8277)]
interface sbIMutablePropertyArray : sbIPropertyArray
{
  /**
   * Adds a new property to the array
   *
   * \param aName  The name of the property
   * \param aValue The value of the property
   */
  void appendProperty(in AString aName,
                      in AString aValue);
};

