/*
//
// BEGIN SONGBIRD GPL
//
// This file is part of the Songbird web player.
//
// Copyright(c) 2005-2007 POTI, Inc.
// http://songbirdnest.com
//
// This file may be licensed under the terms of of the
// GNU General Public License Version 2 (the "GPL").
//
// Software distributed under the License is distributed
// on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either
// express or implied. See the GPL for the specific language
// governing rights and limitations.
//
// You should have received a copy of the GPL along with this
// program. If not, go to http://www.gnu.org/licenses/gpl.html
// or write to the Free Software Foundation, Inc.,
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
//
// END SONGBIRD GPL
//
*/

/**
 * \file sbIPropertiesManager.idl
 * \brief Definition of the sbIPropertiesManager interface
 * \sa List of "see also" files
 */

#include "nsISupports.idl"

interface nsIStringEnumerator;
interface sbIProperty;

/**
* \interface sbIPropertiesManager
* \brief Manager for system wide metadata properties
*
* Components should register properties with this service at startup.
*
* \sa sbIProperty
*/
[scriptable, uuid(c0a9d8fe-cb62-49f8-b4e4-bd98626798cc)]
interface sbIPropertiesManager : nsISupports
{
  /**
   * \brief Get a property object from its name
   * \param aName Name of the property
   * \return Property object for the given property, null if not found
   */
  sbIProperty getProperty(in AString aName);

  /**
   * \brief Add a property into the system
   * \param aProperty Property to add into the system.  An exception is thrown
   * if the property's name is not unique
   */
  void addProperty(in sbIProperty aProperty);
};

/**
* \interface sbIProperty
* \brief System wide metadata property
* \sa sbIPropertyManager
*/
[scriptable, uuid(b01575d3-9c1a-49d0-ba70-61589cb10b65)]
interface sbIProperty : nsISupports
{
  /**
   * \brief Unique name for this property
   */
  readonly attribute AString name;

  /**
   * \brief Bundle key name for the localized name of this property
   */
  readonly attribute AString displayKey;

  /**
   * \brief True if this property has a selection list
   */
  readonly attribute boolean hasValues;

  /**
   * \brief An enumerator of selection list values
   */
  readonly attribute nsIStringEnumerator values;

  /**
   * \brief Display units (does this need to be i18ned?)
   */
  readonly attribute AString units;

  /**
   * \brief Validates the string for this property type
   * \param aValue Value to validate
   * \return Ture if the value is valid for this property, otherwise false
   */
  boolean validate(in AString aValue);

  /**
   * \brief Formats the value for display
   * \param aValue Value to format
   * \return The formatted value
   */
  AString format(in AString aValue);
};

