#include "nsISupports.idl"

interface sbIMediaItem;
interface nsIDOMWindow;

[scriptable, uuid(8d445ad0-3e27-11e2-a25f-0800200c9a66)]
interface sbIArtistProfile : nsISupports
{
  boolean hasArtist(in sbIMediaItem artistMedia);
  void openArtistProfile(in sbIMediaItem artistMedia, in nsIDOMWindow origin);
};
