#include "nsISupports.idl"

interface ngIInternalSearchEngine;

[scriptable, uuid(d154ac90-7953-11e2-b92a-0800200c9a66)]
interface ngIInternalSearchEnginesService : nsISupports
{
  boolean registerInternalSearchEngine(in AString searchEngineAlias, in boolean liveSearch);
  void unregisterInternalSearchEngine(in AString searchEngineAlias);
  ngIInternalSearchEngine getInternalSearchEngine(in AString searchEngineAlias);
};
