/*
//
// BEGIN SONGBIRD GPL
//
// This file is part of the Songbird web player.
//
// Copyright(c) 2005-2007 POTI, Inc.
// http://songbirdnest.com
// 
// This file may be licensed under the terms of of the
// GNU General Public License Version 2 (the "GPL").
// 
// Software distributed under the License is distributed
// on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either
// express or implied. See the GPL for the specific language
// governing rights and limitations.
//
// You should have received a copy of the GPL along with this
// program. If not, go to http://www.gnu.org/licenses/gpl.html
// or write to the Free Software Foundation, Inc.,
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
//
// END SONGBIRD GPL
//
*/

/**
 * \file sbIFeathersManagerListener.idl
 * \brief Callback interface used to listen to Feathers Manager changes
 */

#include "nsISupports.idl"

interface sbILayoutDescription;
interface sbISkinDescription;

/**
* \interface sbIFeathersManagerListener
* \brief Callback interface used to listen to Feathers Manager changes
*
* \sa sbIFeathersManager
*/
[scriptable, uuid(989ca002-eea7-4eff-ae93-2615f89b5581)]
interface sbIFeathersManagerListener : nsISupports
{
  /**
   * \brief Called whenever the Feathers Manager is modified
   */  
  void onFeathersUpdate();

  /**
   * \brief Called when the feathers manager is about to switch feathers
   * \param aLayout Description of the layout to be selected
   * \param aSkin Description of the skin to be selected
   */  
  void onFeathersSelectRequest(in sbILayoutDescription aLayout, 
                               in sbISkinDescription aSkin);
};