/*
//
// BEGIN SONGBIRD GPL
//
// This file is part of the Songbird web player.
//
// Copyright(c) 2005-2007 POTI, Inc.
// http://songbirdnest.com
// 
// This file may be licensed under the terms of of the
// GNU General Public License Version 2 (the "GPL").
// 
// Software distributed under the License is distributed
// on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either
// express or implied. See the GPL for the specific language
// governing rights and limitations.
//
// You should have received a copy of the GPL along with this
// program. If not, go to http://www.gnu.org/licenses/gpl.html
// or write to the Free Software Foundation, Inc.,
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
//
// END SONGBIRD GPL
//
*/

/**
 * \file sbISkinDescription.idl
 * \brief Skin package description
 */

#include "nsISupports.idl"


/**
* \interface sbISkinDescription
* \brief Struct describing the properties of a skin
* \sa sbIFeathersManager
*/
[scriptable, uuid(1f46254a-0746-4a73-956e-263780b5d954)]
interface sbISkinDescription : nsISupports
{

  /**
   * \brief Skin provider name (internalName in install.rdf)
   * The provider name and primary identifier for the skin
   */  
  readonly attribute AString provider;
 
  /**
   * \brief Human readable name
   */
  readonly attribute AString name;

  /**
   * \brief Human readable description
   */
  readonly attribute AString description;
  
  /**
   * \brief Author details
   */  
  readonly attribute AString creator;

  /**
   * \brief Version information
   */  
  readonly attribute AString version;

  /**
   * \brief URL for a preview image
   */  
  readonly attribute AString previewImage;

};