/* -*- Mode: IDL; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* vim: set sw=2 :miv */
/*
//
// BEGIN SONGBIRD GPL
//
// This file is part of the Songbird web player.
//
// Copyright(c) 2005-2008 POTI, Inc.
// http://songbirdnest.com
//
// This file may be licensed under the terms of of the
// GNU General Public License Version 2 (the "GPL").
//
// Software distributed under the License is distributed
// on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either
// express or implied. See the GPL for the specific language
// governing rights and limitations.
//
// You should have received a copy of the GPL along with this
// program. If not, go to http://www.gnu.org/licenses/gpl.html
// or write to the Free Software Foundation, Inc.,
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
//
// END SONGBIRD GPL
//
*/

#include "nsISupports.idl"

/**
 * \interface sbIURLFormatter
 *
 * This interface is identical to the proposed changes to the mozilla
 *  nsIURLFormatter interface as detailed in the bmo bug 430235.
 *
 * Implementors of this interface will replace all instances of the keys
 *  in the propertyBag for their associated keys in the string passed in,
 *  or the preference value it refers to. They may have a set of pre-defined
 *  default keys.
 *
 * The sbURLFormatter object predefines these keys to match the impl defined
 *  in the nsURLFormatter class:
 *     LOCALE
 *     VENDOR
 *     NAME
 *     ID
 *     VERSION
 *     APPBUILDID
 *     PLATFORMVERSION
 *     PLATFORM_VERSION
 *     APP
 *     OS
 *     XPCOMABI
 *
 * The sbURLFormatter object also defines these keys using the impl defined
 *  in the nsUpdateService class.
 *     DISTRIBUTION
 *     DISTRIBUTION_VERSION
 *     OS_VERSION
 *     PRODUCT
 *     BUILD_ID
 *     BUILD_TARGET
 *     CHANNEL
 *
 * "@songbirdnest.com/moz/sburlformatter;1"
 * Use get service with this component.
 */

interface nsIPropertyBag;

[scriptable, uuid(b4487e9b-6c4f-49ce-9255-057c4e88c3c4)]
interface sbIURLFormatter : nsISupports
{
  /** 
   * formatURL - Formats a string URL
   *
   * @param aFormat string 
   * @param aMappings PropertyBag - additional key/value pairs to replace beyond
   *   the defaults. 
   */
  AString formatURL(in AString aFormat, [optional] in nsIPropertyBag aMappings);

  /** 
   * formatURLPref - Formats a string URL stored in a pref
   *
   * @param aFormat string 
   * @param aMappings PropertyBag - additional key/value pairs to replace beyond
   *   the defaults. 
   */
  AString formatURLPref(in AString aPref, [optional] in nsIPropertyBag aMappings);

};


//
// C++ defs.
//

%{C++
#define SB_URLFORMATTER_CONTRACTID \
          "@songbirdnest.com/moz/sburlformatter;1"
%}C++

