/*
//
// BEGIN SONGBIRD GPL
// 
// This file is part of the Songbird web player.
//
// Copyright© 2006 POTI, Inc.
// http://songbirdnest.com
// 
// This file may be licensed under the terms of of the
// GNU General Public License Version 2 (the “GPL”).
// 
// Software distributed under the License is distributed 
// on an “AS IS” basis, WITHOUT WARRANTY OF ANY KIND, either 
// express or implied. See the GPL for the specific language 
// governing rights and limitations.
//
// You should have received a copy of the GPL along with this 
// program. If not, go to http://www.gnu.org/licenses/gpl.html
// or write to the Free Software Foundation, Inc., 
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
// 
// END SONGBIRD GPL
//
*/

/**
* \file sbIMetadataBackscanner.idl
* \brief The Metadata Backscanner scans unscanned media items for new metadata.
*/
#include "nsISupports.idl"

[scriptable, uuid(6FE563F3-A217-4e16-A6C5-52BA0F3C09DF)]
interface sbIMetadataBackscanner : nsISupports
{
  attribute PRUint32 scanInterval;

  attribute PRUint32 scannedMediaCount;
  attribute PRUint32 totalMediaCount;

  attribute PRUint32 updateQueueSize;

  attribute AString  currentFile;

  void start();
  void stop();

};
