/*
//
// BEGIN SONGBIRD GPL
// 
// This file is part of the Songbird web player.
//
// Copyright© 2006 Pioneers of the Inevitable LLC
// http://songbirdnest.com
// 
// This file may be licensed under the terms of of the
// GNU General Public License Version 2 (the “GPL”).
// 
// Software distributed under the License is distributed 
// on an “AS IS” basis, WITHOUT WARRANTY OF ANY KIND, either 
// express or implied. See the GPL for the specific language 
// governing rights and limitations.
//
// You should have received a copy of the GPL along with this 
// program. If not, go to http://www.gnu.org/licenses/gpl.html
// or write to the Free Software Foundation, Inc., 
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
// 
// END SONGBIRD GPL
//
*/

#include "nsISupports.idl"
#include "sbIMetadataHandler.idl"

//{ 0x3ebc067f, 0xe52d, 0x4041, { 0xa5, 0xe4, 0x5c, 0x21, 0x7d, 0x4a, 0x5f, 0xbe } }

[scriptable, uuid(3EBC067F-E52D-4041-A5E4-5C217D4A5FBE)]
interface sbIMetadataManager : nsISupports
{
  sbIMetadataHandler GetHandlerForMediaURL(in wstring strURL);
};