/*
//
// BEGIN SONGBIRD GPL
// 
// This file is part of the Songbird web player.
//
// Copyright© 2006 POTI, Inc.
// http://songbirdnest.com
// 
// This file may be licensed under the terms of of the
// GNU General Public License Version 2 (the “GPL”).
// 
// Software distributed under the License is distributed 
// on an “AS IS” basis, WITHOUT WARRANTY OF ANY KIND, either 
// express or implied. See the GPL for the specific language 
// governing rights and limitations.
//
// You should have received a copy of the GPL along with this 
// program. If not, go to http://www.gnu.org/licenses/gpl.html
// or write to the Free Software Foundation, Inc., 
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
// 
// END SONGBIRD GPL
//
*/

#include "nsISupports.idl"
#include "nsIChannel.idl"
#include "sbIMetadataValues.idl"

//{ 0x919ff2d3, 0x616d, 0x4035, { 0xa5, 0x2f, 0x8, 0xc2, 0x39, 0xf3, 0x34, 0xee } }

[scriptable, uuid(919FF2D3-616D-4035-A52F-08C239F334EE)]
interface sbIMetadataHandler : nsISupports
{
  PRInt32 Vote( in wstring url );
  void SupportedMIMETypes(out PRUint32 nMIMECount, [array, size_is (nMIMECount), retval] out wstring aMIMETypes);
  void SupportedFileExtensions(out PRUint32 nExtCount, [array, size_is (nExtCount), retval] out wstring aExts);

  nsIChannel GetChannel();
  PRInt32 SetChannel(in nsIChannel urlChannel);

  PRInt32 Read();
  PRInt32 Write();

  sbIMetadataValues GetValuesMap();
  void SetValuesMap(in sbIMetadataValues values);

  void OnChannelData( in nsISupports channel );
  PRBool GetCompleted();
  void Close();
};