/*
//
// BEGIN SONGBIRD GPL
// 
// This file is part of the Songbird web player.
//
// Copyright© 2006 POTI, Inc.
// http://songbirdnest.com
// 
// This file may be licensed under the terms of of the
// GNU General Public License Version 2 (the “GPL”).
// 
// Software distributed under the License is distributed 
// on an “AS IS” basis, WITHOUT WARRANTY OF ANY KIND, either 
// express or implied. See the GPL for the specific language 
// governing rights and limitations.
//
// You should have received a copy of the GPL along with this 
// program. If not, go to http://www.gnu.org/licenses/gpl.html
// or write to the Free Software Foundation, Inc., 
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
// 
// END SONGBIRD GPL
//
*/

/**
* \file sbIMetadataValues.idl
* \brief A map of value+type pairs, keyed by string.
*/
#include "nsISupports.idl"

/**
* \interface sbIMetadataValues sbIMetadataValues.h
* \brief A map of value+type pairs, keyed by string.
*
* This object is passed from and to a sbIMetadataHandler for reading or
* writing the metadata set of a track.
*
* The list of supported metadata keys is:
*
* The type enumeration is:
*
* \TODO Make a list of keys.  Make a type enumeration.
* \sa sbIMetadataHandler
*/
[scriptable, uuid(EC39DE03-8918-4369-951E-0A04BD9CF663)]
interface sbIMetadataValues : nsISupports
{
  /**
  * \brief The number of values stored internally
  */
  readonly attribute PRInt32 numValues;

  /**
  * \brief The N'th key in the internal map
  */
  AString getKey( in PRInt32 N );

  /**
  * \brief Assign a value to the internal map
  * \param aKey The key index to receive the incoming value
  * \param aValue The value to assign
  * \param aType The type of the value
  */
  void setValue( in AString aKey, in AString aValue, in PRInt32 aType );

  /**
  * \brief Retrieve a value from the internal map
  * \param aKey The key index to find the value
  * \return The value string at that key
  */
  AString getValue( in AString aKey );

  /**
  * \brief Retrieve a value type from the internal map
  * \param aKey The key index to find the value type
  * \return The type enumeration at that key
  */
  PRInt32 getType( in AString aKey );

  /**
  * \brief Clear the internal map and erase all the values
  */
  void clear();
};