/*
//
// BEGIN SONGBIRD GPL
// 
// This file is part of the Songbird web player.
//
// Copyright(c) 2005-2008 POTI, Inc.
// http://songbirdnest.com
// 
// This file may be licensed under the terms of of the
// GNU General Public License Version 2 (the "GPL").
// 
// Software distributed under the License is distributed 
// on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either 
// express or implied. See the GPL for the specific language 
// governing rights and limitations.
//
// You should have received a copy of the GPL along with this 
// program. If not, go to http://www.gnu.org/licenses/gpl.html
// or write to the Free Software Foundation, Inc., 
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
// 
// END SONGBIRD GPL
//
*/

#include "nsISupports.idl"

interface nsIPropertyBag;
interface nsISimpleEnumerator;

interface sbIDevice;
interface sbIDeviceCompatibility;

/**
 * \interface sbIDeviceController
 * \brief [UNIMPLEMENTED UNTIL AFTER 0.3]
 */
[scriptable, uuid(b4b7ed5d-85f2-4d0b-a7c6-f235acad3fc0)]
interface sbIDeviceController : nsISupports
{
  /**
   * Unique identifier for the controller
   */
  readonly attribute nsIDPtr id;

  /**
   * A human readable name, optional?
   */
  readonly attribute AString name;

  /**
   * The nsID of an sbIDeviceMarshall implementor that the controller wishes to
   * use. This must be valid or the controller will never be instantiated!
   */
  readonly attribute nsIDPtr marshallId;

  /**
   * 
   */
  sbIDeviceCompatibility getCompatibility(in nsIPropertyBag aParams);

  /**
   * Constructs a device based on the given parameters.
   */
  sbIDevice createDevice(in nsIPropertyBag aParams);

  /**
   * Determines if a device is currently controlled by the controller
   */
  boolean controlsDevice(in sbIDevice aDevice);

  /**
   * Connects all devices.
   */
  void connectDevices();

  /**
   * Disconnects all devices.
   */
  void disconnectDevices();

  /**
   * Called when the controller should release a single device.
   */
  void releaseDevice(in sbIDevice aDevice);

  /**
   * Called when the controller should release all registered devices.
   */
  void releaseDevices();
};

%{C++
#include "nsCOMPtr.h"
#include "nsIComponentManager.h"
#include "nsICategoryManager.h"
#include "nsIServiceManager.h"
#include "nsStringGlue.h"
#include "nsXPCOMCID.h"

class nsIFile;
struct nsModuleComponentInfo;

#define SB_DEVICE_CONTROLLER_CATEGORY "songbird-device-controller"

/**
 * Put this in your module definition file. Give your class name. Then your
 * moduleInfo should look something like this:
 *
 *   NS_GENERIC_FACTORY_CONSTRUCTOR(sbSampleController);
 *   SB_DEVICE_CONTROLLER_REGISTERSELF(sbSampleController);
 *
 *   static nsModuleComponentInfo components[] =
 *   {
 *     {
 *       CLASSNAME, 
 *       CID,
 *       CONTRACTID,
 *       sbSampleControllerConstructor,
 *       sbSampleControllerRegisterSelf,
 *       sbSampleControllerUnregisterSelf
 *     }
 *   };
 *
 *   NS_IMPL_NSGETMODULE("Sample Controller", components)
 */
#define SB_DEVICE_CONTROLLER_REGISTERSELF(_name)                               \
                                                                               \
  static NS_METHOD _name##RegisterSelf(nsIComponentManager* aCompMgr,          \
                                       nsIFile* aPath,                         \
                                       const char* registryLocation,           \
                                       const char* componentType,              \
                                       const nsModuleComponentInfo* info);     \
                                                                               \
  static NS_METHOD _name##UnregisterSelf(nsIComponentManager* aCompMgr,        \
                                         nsIFile* aPath,                       \
                                         const char* registryLocation,         \
                                         const nsModuleComponentInfo* info)

/**
 * Stick this in your implementation file. Give your class name.
 */
#define SB_DEVICE_CONTROLLER_REGISTERSELF_IMPL(_name)                          \
                                                                               \
  NS_METHOD                                                                    \
  _name##RegisterSelf(nsIComponentManager* aCompMgr,                           \
                      nsIFile* aPath,                                          \
                      const char* registryLocation,                            \
                      const char* componentType,                               \
                      const nsModuleComponentInfo* info)                       \
  {                                                                            \
    nsresult rv;                                                               \
    nsCOMPtr<nsICategoryManager> catMan =                                      \
      do_GetService(NS_CATEGORYMANAGER_CONTRACTID, &rv);                       \
    NS_ENSURE_SUCCESS(rv, rv);                                                 \
    nsID id;                                                                   \
    rv = this->GetIdInPlace(&id);                                              \
    NS_ENSURE_SUCCESS(rv, rv);                                                 \
    nsCAutoString idString(id.ToString());                                     \
    NS_ENSURE_STATE(!idString.IsEmpty());                                      \
    nsXPIDLCString prevEntry;                                                  \
    rv = catMan->AddCategoryEntry(SB_DEVICE_CONTROLLER_CATEGORY,               \
                                  idString.get(),                              \
                                  info->mContractID,                           \
                                  PR_TRUE, PR_TRUE,                            \
                                  getter_Copies(prevEntry));                   \
    NS_ENSURE_SUCCESS(rv, rv);                                                 \
    NS_WARN_IF_FALSE(prevEntry.IsEmpty(),                                      \
                     "Another controller was registered with that id!");       \
    return NS_OK;                                                              \
  }                                                                            \
                                                                               \
  NS_METHOD                                                                    \
  _name##UnregisterSelf(nsIComponentManager* aCompMgr,                         \
                        nsIFile* aPath,                                        \
                        const char* registryLocation,                          \
                        const nsModuleComponentInfo* info)                     \
  {                                                                            \
    nsresult rv;                                                               \
    nsCOMPtr<nsICategoryManager> catMan =                                      \
      do_GetService(NS_CATEGORYMANAGER_CONTRACTID, &rv);                       \
    NS_ENSURE_SUCCESS(rv, rv);                                                 \
    nsID id;                                                                   \
    rv = this->GetIdInPlace(&id);                                              \
    NS_ENSURE_SUCCESS(rv, rv);                                                 \
    nsCAutoString idString(id.ToString());                                     \
    NS_ENSURE_STATE(!idString.IsEmpty());                                      \
    rv = catMan->DeleteCategoryEntry(SB_DEVICE_CONTROLLER_CATEGORY,            \
                                     idString.get(),                           \
                                     PR_TRUE);                                 \
    NS_ENSURE_SUCCESS(rv, rv);                                                 \
    return NS_OK;                                                              \
  }
%}
