#preedTODO: add copyright
DEPTH = ../../..
topsrcdir = /media/disk/Linux/makepkg/songbird
srcdir = /media/disk/Linux/makepkg/songbird/extensions/mashTape/chrome
VPATH = /media/disk/Linux/makepkg/songbird/extensions/mashTape/chrome
  
include $(DEPTH)/build/autodefs.mk

IS_EXTENSION = 1

JAR_MANIFEST = jar.mn.in

include $(topsrcdir)/build/rules.mk
