#preedTODO: add copyright
DEPTH = ../../..
topsrcdir = /media/disk/Linux/makepkg/songbird
srcdir = /media/disk/Linux/makepkg/songbird/extensions/lastfm/components
VPATH = /media/disk/Linux/makepkg/songbird/extensions/lastfm/components

include $(DEPTH)/build/autodefs.mk

IS_EXTENSION = 1

SONGBIRD_COMPONENTS = $(srcdir)/sbLastFm.js \
                      $(srcdir)/sbLastFmProtocol.js \
                      $(NULL)

include $(topsrcdir)/build/rules.mk
