/*
//
// BEGIN SONGBIRD GPL
// 
// This file is part of the Songbird web player.
//
// Copyright(c) 2005-2009 POTI, Inc.
// http://songbirdnest.com
// 
// This file may be licensed under the terms of of the
// GNU General Public License Version 2 (the "GPL").
// 
// Software distributed under the License is distributed 
// on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either 
// express or implied. See the GPL for the specific language 
// governing rights and limitations.
//
// You should have received a copy of the GPL along with this 
// program. If not, go to http://www.gnu.org/licenses/gpl.html
// or write to the Free Software Foundation, Inc., 
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
// 
// END SONGBIRD GPL
//
*/

/**
 * \file sbITranscodeBatchJob.idl
 * \brief Transcode a batch of media items
 */
#include "nsISupports.idl"
#include "sbITranscodeProfile.idl"

interface sbIMediaItem;

[scriptable, uuid(b197e79d-a015-4fc0-bcf3-98045281c60b)]
interface sbITranscodeBatchJobItem : nsISupports
{
  /**
   * \brief The sbIMediaItem to transcode
   */
  attribute sbIMediaItem mediaItem;

  /**
   * \brief The file to write the transcoded media to
   *
   * Note: The directory that this file is in must exist.
   *       The file MAY exist; it'll be overwritten if it does.
   */
  attribute nsIFile destinationFile;
};

%{C++
#define SONGBIRD_TRANSCODEBATCHJOBITEM_DESCRIPTION          \
  "Songbird Transcode Batch Job Item Component"
#define SONGBIRD_TRANSCODEBATCHJOBITEM_CONTRACTID              \
  "@songbirdnest.com/Songbird/Transcode/BatchJobItem;1"
#define SONGBIRD_TRANSCODEBATCHJOBITEM_CLASSNAME               \
  "Songbird Batch Job Item"
#define SONGBIRD_TRANSCODEBATCHJOBITEM_CID                     \
{ /* 59d47492-e0c5-4cb5-8276-3fd61f33c3b6 */              \
  0x59d47492,                                             \
  0xe0c5,                                                 \
  0x4cb5,                                                 \
  {0x82, 0x76, 0x3f, 0xd6, 0x1f, 0x33, 0xc3, 0xb6}        \
}
%}

/**
 * \interface sbITranscodeBatchJob
 * \brief An object that manages transcoding a set of streams to a common
 *        destination format.
 *       
 * Manages transcoding N items concurrently, and reporting progress/errors for
 * the entire batch.
 *
 * \sa sbITranscodeJob
 * \sa sbIJobProgress
 * \sa sbIJobCancelable
 */
[scriptable, uuid(ce98321c-c0eb-4628-b153-ac303de0a7bf)]
interface sbITranscodeBatchJob : nsISupports
{
  /**
   * \brief The encoding profile to use
   *
   * A profile description for the transcode.
   */
  attribute sbITranscodeProfile profile;

  /**
   * \brief Profile to use for album art in the target file
   *
   * Any album art will be transcoded to match this profile before adding
   * to the target file.
   */ 
  attribute sbITranscodeImageProfile imageProfile;

  /**
   * \brief Array of sbITranscodeBatchJobItems to transcode.
   */
  attribute nsIArray items;

  /**
   * \brief The number of transcode jobs to run concurrently. Defaults to 1.
   */
  attribute unsigned short concurrentTranscodes;


  /**
   * \brief Start the transcoding operation
   *
   * Caller should monitor progress via sbIJobProgress
   */
  void transcodeBatch();
};


