/*
//
// BEGIN SONGBIRD GPL
// 
// This file is part of the Songbird web player.
//
// Copyright© 2006 Pioneers of the Inevitable LLC
// http://songbirdnest.com
// 
// This file may be licensed under the terms of of the
// GNU General Public License Version 2 (the “GPL”).
// 
// Software distributed under the License is distributed 
// on an “AS IS” basis, WITHOUT WARRANTY OF ANY KIND, either 
// express or implied. See the GPL for the specific language 
// governing rights and limitations.
//
// You should have received a copy of the GPL along with this 
// program. If not, go to http://www.gnu.org/licenses/gpl.html
// or write to the Free Software Foundation, Inc., 
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
// 
// END SONGBIRD GPL
//
*/

#include "nsISupports.idl"

interface sbIDeviceBase;

/**
 * This is the DeviceManager service.
 * Make sure to use getService rather than createInstance when using.
 */
[scriptable, uuid(4403C45D-0BB8-47cb-AB89-2221F62E5614)]
interface sbIDeviceManager : nsISupports
{
  /**
   * The number of device categories currently registered
   */
	readonly attribute PRUint32 deviceCategoriesCount;

  /**
   * Gets the category (nsAString) of the device at the specified index
   *
   * @param aIndex - the index of the device
   */
	AString getDeviceCategoryString(in PRUint32 aIndex);

  /**
   * Returns a registered and initialized device
   *
   * @param aIndex - the index of the device
   */
	sbIDeviceBase getDeviceByIndex(in PRUint32 aIndex);

  /**
   * Returns a registered and initialized device
   *
   * @param aDeviceCategory - a category string identifying the device
   */
	sbIDeviceBase getDeviceByString(in AString aDeviceCategory);
};
