/*
 * Written by Logan F. Smyth © 2009
 * http://logansmyth.com
 * me@logansmyth.com
 * 
 * Feel free to use/modify this code, but if you do
 * then please at least tell me!
 *
 */


#include "nsISupports.idl"

interface sbIDbusConnection;

[scriptable, uuid(bc3f9c62-9a5f-47e8-a00f-49d80f3bb6c9)]
interface sbIMethodHandler : nsISupports
{
  void handleMethod(in string interface_name, in string path, in string member);
};


[scriptable, uuid(a8159f8d-7970-40d0-bd08-8d0adf69e435)]
interface sbIMprisPlugin : sbIMethodHandler
{
  attribute sbIDbusConnection dbus;
  attribute boolean debug_mode;
  void init(in boolean debug);
  void getMetadata(in long track_num);
  void setMetadata(in long track_num);
  void getStatus();
  void getCaps();
  void addTrack(in AString uri, in boolean play_now);
  void delTrack(in long track_num);
};


[scriptable, uuid(4c809340-0f6f-4122-b242-d4e900bed92b)]
interface sbIDbusConnection : nsISupports
{
  attribute boolean debug_mode;
    
  long init(in string name, in boolean debug);
  void setMatch(in string match);
  void check();
  long end();
  
  void prepareSignal(in string path, in string inter, in string name);
  void sendSignal();
  
  void setMethodHandler(in sbIMethodHandler handler);

  long getInt32Arg();
  boolean getBoolArg();
  string getStringArg();
  
  void setUInt32Arg(in unsigned long val);
  void setInt32Arg(in long val);
  void setUInt16Arg(in unsigned short val);
  void setStringArg(in string val);
//  void setStringArg(in AString val);
  void setDictSSEntryArg(in string key, in AString val);
  void setDictSIEntryArg(in string key, in unsigned long val);

  void openDictEntryArray();
  void closeDictEntryArray();

  void openStruct();
  void closeStruct();

};
