/*
//
// BEGIN SONGBIRD GPL
// 
// This file is part of the Songbird web player.
//
// Copyright(c) 2005-2007 POTI, Inc.
// http://songbirdnest.com
// 
// This file may be licensed under the terms of of the
// GNU General Public License Version 2 (the "GPL").
// 
// Software distributed under the License is distributed 
// on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either 
// express or implied. See the GPL for the specific language 
// governing rights and limitations.
//
// You should have received a copy of the GPL along with this 
// program. If not, go to http://www.gnu.org/licenses/gpl.html
// or write to the Free Software Foundation, Inc., 
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
// 
// END SONGBIRD GPL
//
 */

#include "nsISupports.idl"
#include "sbIDeviceBase.idl"

[scriptable, uuid(a20bf454-673b-4308-8898-93f2b001d4e9)]
interface sbIUSBMassStorageDevice : sbIDeviceBase
{
  readonly attribute AString deviceModel;
  readonly attribute AString deviceVendor;
  readonly attribute AString deviceSerialNumber;

  PRBool OnUSBDeviceMounted(in AString deviceMountPath);

  PRBool OnUSBDeviceEvent(in PRBool deviceAdded, 
    in AString deviceName, 
    in AString deviceIdentifier);
};


// {4C4E501E-D117-41a6-99A0-59E8AFEFB61D}
//{ 0x4c4e501e, 0xd117, 0x41a6, { 0x99, 0xa0, 0x59, 0xe8, 0xaf, 0xef, 0xb6, 0x1d } };

[scriptable, uuid(4C4E501E-D117-41a6-99A0-59E8AFEFB61D)]
interface sbIUSBMassStorageDeviceHandler : nsISupports
{



  PRBool CanHandleDevice(in AString deviceIdentifier, 
    in AString devicePath, 
    in AString deviceVendor, 
    in AString deviceModel, 
    in AString deviceSerialNumber);

  //SupportedMIMETypes();
  //SupportedFileTypes();

  PRInt32 OnDeviceConnect(in AString deviceIdentifier, 
    in AString devicePath);

  PRInt32 OnDeviceDisconnect(in AString deviceIdentifier, 
    in AString devicePath);

  PRInt32 OnPrepareUpload(in AString deviceIdentifier, 
    in AString devicePath, 
    in AString strSourceURL, 
    out AString strDefaultDestURL);
  
  PRInt32 OnCompleteUpload(in AString deviceIdentifier, 
    in AString devicePath, 
    in AString strSourceURL ,
    in AString strDestURL);

  PRInt32 OnPrepareDownload(in AString deviceIdentifier, 
    in AString devicePath, 
    in AString strSourceURL, 
    out AString strDefaultDestURL);

  PRInt32 OnCompleteDownload(in AString deviceIdentifier, 
    in AString devicePath, 
    in AString strSourceURL, 
    out AString strDefaultDestURL);

};