/* -*- Mode: IDL; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* vim: set sw=2 :miv */
/*
//
// BEGIN NIGHTINGALE GPL
//
// This file is part of the Nightingale web player.
//
// Copyright(c) 2005-2008 POTI, Inc.
// http://getnightingale.com
//
// This file may be licensed under the terms of of the
// GNU General Public License Version 2 (the "GPL").
//
// Software distributed under the License is distributed
// on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either
// express or implied. See the GPL for the specific language
// governing rights and limitations.
//
// You should have received a copy of the GPL along with this
// program. If not, go to http://www.gnu.org/licenses/gpl.html
// or write to the Free Software Foundation, Inc.,
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
//
// END NIGHTINGALE GPL
//
*/

//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
//
// Interface description for the Nightingale string bundle service interface.
//
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------

#include "nsISupports.idl"


/**
 * \interface sbIStringBundleService
 * \brief Interface for the Nightingale string bundle service.  Instantiate as a
 *        component service.
 *
 * "@getnightingale.com/Nightingale/stringbundle;1"
 */

interface nsIStringBundle;

[scriptable, uuid(fd613e37-5cd0-43ed-af74-f18191f634f8)]
interface sbIStringBundleService : nsISupports
{
  /**
   * \brief Main Nightingale string bundle.  Thread-safe.
   */

  readonly attribute nsIStringBundle bundle;


  /**
   * \brief Main Nightingale brand string bundle.  Thread-safe.
   */

  readonly attribute nsIStringBundle brandBundle;
};


//
// C++ defs.
//

%{C++
#define SB_STRINGBUNDLESERVICE_CONTRACTID \
          "@getnightingale.com/Nightingale/stringbundle;1"
%}C++

