/*
 //
// BEGIN SONGBIRD GPL
// 
// This file is part of the Songbird web player.
//
// Copyright(c) 2005-2008 POTI, Inc.
// http://songbirdnest.com
// 
// This file may be licensed under the terms of of the
// GNU General Public License Version 2 (the "GPL").
// 
// Software distributed under the License is distributed 
// on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either 
// express or implied. See the GPL for the specific language 
// governing rights and limitations.
//
// You should have received a copy of the GPL along with this 
// program. If not, go to http://www.gnu.org/licenses/gpl.html
// or write to the Free Software Foundation, Inc., 
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
// 
// END SONGBIRD GPL
//
 */

#include "nsISupports.idl"

interface nsIVariant;

interface sbIMediacore;
interface sbIMediacoreError;
interface sbIMediacoreEvent;
interface sbIMediacoreSimpleEqualizer;
interface sbIMediacoreBalanceControl;

interface sbIMediacorePlaybackControl;
interface sbIMediacoreVolumeControl;

interface sbIMediacoreCapabilities;

interface sbIMediacoreSequencer;

[scriptable, uuid(c9eb7de1-87fc-4eea-886e-6202cae826bc)]
interface sbIMediacoreManager : nsISupports
{
  /**
   * The primary core is always used to play user content. 
   * 
   * If you need a mediacore for background tasks of any kind, it is 
   * preferable to create a new instance.
   *
   * Setting the primaryCore will have the following effect:
   *
   * 1. Playback will be stopped for the current sequence.
   * 2. A new sequence will be generated for the new primary core.
   * 3. The new sequence is set on the new primary core.
   */
  attribute sbIMediacore primaryCore;

  readonly attribute sbIMediacoreBalanceControl  balanceControl;
  readonly attribute sbIMediacoreVolumeControl   volumeControl;

  readonly attribute sbIMediacoreSimpleEqualizer equalizer;
  readonly attribute sbIMediacorePlaybackControl playbackControl;

  readonly attribute sbIMediacoreCapabilities    capabilities;

  /**
   * The current sequencer used to generate and manage playback sequences.
   *
   * Setting the sequencer will have the following effect:
   *
   * 1. Current sequences remain unaffected.
   * 2. When playback of current sequences is complete, the new sequencer
   *    is used to 
   */
  attribute sbIMediacoreSequencer sequencer;

  /**
   * Create a new event
   * 
   * @param aType The type of the event; should be one of the COMMAND_* or
   *              EVENT_* constants on the sbIMediacoreEvent.
   *
   * @param aData (Optional) The data to pass to any listeners that would
   *              receive this event.
   *
   * @param aOrigin (Optional) Some indication of the source of the event.
   *
   * @param aError (Optional) An error associated with the event
   * 
   * @see sbIMediacoreEvent
   * @see sbIMediacoreEventTarget
   * @see sbIMediacoreEventListener
   */
  sbIMediacoreEvent createEvent(in unsigned long aType,
                                in sbIMediacore aOrigin,
                                [optional] in nsIVariant aData,
                                [optional] in sbIMediacoreError aError);

  //void playURI(in nsIURI aUri);
  //void playMediaListView(in sbIMediaListView aView, in unsigned long aIndex);
};

%{C++

#define SB_MEDIACOREMANAGER_DESCRIPTION    \
  "Songbird Mediacore Manager"
#define SB_MEDIACOREMANAGER_CONTRACTID     \
  "@songbirdnest.com/Songbird/Mediacore/Manager;1"
#define SB_MEDIACOREMANAGER_CLASSNAME      \
  "sbMediacoreManager"
#define SB_MEDIACOREMANAGER_CID               \
{ /*{47bb93c8-dba7-464b-8f93-8d71659ab127}*/  \
  0x47bb93c8,                                 \
  0xdba7,                                     \
  0x464b,                                     \
  { 0x8f, 0x93, 0x8d, 0x71, 0x65, 0x9a, 0xb1, 0x27 } \
}

%}