/* -*- Mode: IDL; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* vim: set sw=2 :miv */
/*
 *=BEGIN NIGHTINGALE GPL
 *
 * This file is part of the Nightingale web player.
 *
 * Copyright(c) 2005-2009 POTI, Inc.
 * http://www.getnightingale.com
 *
 * This file may be licensed under the terms of of the
 * GNU General Public License Version 2 (the ``GPL'').
 *
 * Software distributed under the License is distributed
 * on an ``AS IS'' basis, WITHOUT WARRANTY OF ANY KIND, either
 * express or implied. See the GPL for the specific language
 * governing rights and limitations.
 *
 * You should have received a copy of the GPL along with this
 * program. If not, go to http://www.gnu.org/licenses/gpl.html
 * or write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 *=END NIGHTINGALE GPL
 */

#include "nsISupports.idl"

/**
 * \interface sbIFileUtils
 *
 *   This interface provides various file utilities.
 *
 * "@getnightingale.com/Nightingale/FileUtils;1"
 * Use get service with this component.
 */

interface nsIFile;

[scriptable, uuid(1bd939fc-1dd2-11b2-a0ef-d36ceb4e7caf)]
interface sbIFileUtils : nsISupports
{
  /**
   * \brief Current working directory.
   * \see CurWorkD
   */

  attribute nsIFile currentDir;
};


//
// C++ defs.
//

%{C++
#define SB_FILEUTILS_CONTRACTID \
          "@getnightingale.com/Nightingale/FileUtils;1"
%}C++

