/* -*- Mode: IDL; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* vim: set sw=2 :miv */
/*
 *=BEGIN SONGBIRD GPL
 *
 * This file is part of the Songbird web player.
 *
 * Copyright(c) 2005-2011 POTI, Inc.
 * http://www.songbirdnest.com
 *
 * This file may be licensed under the terms of of the
 * GNU General Public License Version 2 (the ``GPL'').
 *
 * Software distributed under the License is distributed
 * on an ``AS IS'' basis, WITHOUT WARRANTY OF ANY KIND, either
 * express or implied. See the GPL for the specific language
 * governing rights and limitations.
 *
 * You should have received a copy of the GPL along with this
 * program. If not, go to http://www.gnu.org/licenses/gpl.html
 * or write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 *=END SONGBIRD GPL
 */

#include "nsISupports.idl"

/**
 * \interface sbIFileUtils
 *
 *   This interface provides various file utilities.
 *
 * "@songbirdnest.com/Songbird/FileUtils;1"
 * Use get service with this component.
 */

interface nsIFile;

[scriptable, uuid(466b66d9-7007-48d8-aee1-b600e7745be8)]
interface sbIFileUtils : nsISupports
{
  /**
   * \brief Current working directory.
   * \see CurWorkD
   */

  attribute nsIFile currentDir;

  /**
   * \brief Returns a file's case-sensitive path (Windows-only)
   *
   * \param aFilePath   File path
   *
   * \return Case-sensitive path or null
   */
  AString getExactPath(in AString aFilePath);
};


//
// C++ defs.
//

%{C++
#define SB_FILEUTILS_CONTRACTID \
          "@songbirdnest.com/Songbird/FileUtils;1"
%}C++

