/*
 //
// BEGIN SONGBIRD GPL
// 
// This file is part of the Songbird web player.
//
// Copyright(c) 2005-2008 POTI, Inc.
// http://songbirdnest.com
// 
// This file may be licensed under the terms of of the
// GNU General Public License Version 2 (the "GPL").
// 
// Software distributed under the License is distributed 
// on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either 
// express or implied. See the GPL for the specific language 
// governing rights and limitations.
//
// You should have received a copy of the GPL along with this 
// program. If not, go to http://www.gnu.org/licenses/gpl.html
// or write to the Free Software Foundation, Inc., 
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
// 
// END SONGBIRD GPL
//
 */

#include "nsISupports.idl"

interface sbIJobProgress;
interface nsIDOMWindow;


/**
 * \interface sbIJobProgressService
 * \brief The beginnings of a service to track all background tasks
 *
 * This interface will eventually become a generic place to 
 * register long-running sbIJobProgress implementing tasks.
 *
 * Until this materializes all sbIJobProgressService can do is
 * help launch a modal job progress dialog.
 *
 * \note This interface is guaranteed to change
 */
[scriptable, uuid(00aae850-90d4-11dd-ad8b-0800200c9a66)]
interface sbIJobProgressService : nsISupports
{

  /**
   * \brief Display a progress dialog for an object implementing sbIJobProgress.
   *
   * If the job has not completed in a given amount of time, display
   * a modal progress dialog. 
   *
   * \param aJobProgress    sbIJobProgress interface to be displayed.
   * \param aWindow         Parent window for the dialog. Can be null.
   * \param aTimeout        Time to wait before opening a dialog. 
   *                        Defaults to 1 second.  Pass 0 to open 
   *                        the dialog immediately.
   */  
  void showProgressDialog(in sbIJobProgress aJobProgress,
                          in nsIDOMWindow aWindow, 
                          in unsigned long aTimeout);
};
