/*
 //
// BEGIN SONGBIRD GPL
// 
// This file is part of the Songbird web player.
//
// Copyright© 2006 Pioneers of the Inevitable LLC
// http://songbirdnest.com
// 
// This file may be licensed under the terms of of the
// GNU General Public License Version 2 (the “GPL”).
// 
// Software distributed under the License is distributed 
// on an “AS IS” basis, WITHOUT WARRANTY OF ANY KIND, either 
// express or implied. See the GPL for the specific language 
// governing rights and limitations.
//
// You should have received a copy of the GPL along with this 
// program. If not, go to http://www.gnu.org/licenses/gpl.html
// or write to the Free Software Foundation, Inc., 
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
// 
// END SONGBIRD GPL
//
 */

#include "nsISupports.idl"
#include "IDatabaseQuery.idl"

[scriptable, uuid(ca5c9b2c-e061-4c98-8333-9c839efc0d7f)]
interface sbIMediaLibrary : nsISupports
{
  void SetQueryObject(in sbIDatabaseQuery queryObj);
  sbIDatabaseQuery GetQueryObject();

  void CreateDefaultLibrary();

  wstring AddMedia(in wstring strMediaURL, in PRUint32 nMetaKeyCount, [array, size_is (nMetaKeyCount)] in wstring aMetaKeys, 
    in PRUint32 nMetadataValueCount, [array, size_is (nMetadataValueCount)] in wstring aMetadataValues, in PRBool bCheckForUniqueFileName, in PRBool bWillRunLater);

  PRBool RemoveMediaByURL(in wstring strMediaURL, in PRBool bWillRunLater);
  PRBool RemoveMediaByGUID(in wstring mediaGUID, in PRBool bWillRunLater);
  PRBool PurgeDefaultLibrary(in PRBool bWillRunLater);

  wstring FindByGUID(in wstring mediaGUID);
  wstring FindByURL(in wstring strURL); 

  void AddColumn(in wstring strColumn, in wstring strDataType);
  void DeleteColumn(in wstring strColumn);

  void GetColumnInfo();
  void SetColumnInfo(in wstring strColumn, in wstring strReadableName, in PRBool isVisible, 
    in PRBool defaultVisibility, in PRBool isMetadata, in PRInt32 sortWeight,
    in PRInt32 colWidth, in PRBool bWillRunLater);

  void GetMetadataFields(out PRUint32 nMetadataFieldCount, [array, size_is (nMetadataFieldCount), retval] out wstring aMetadataFields);
  void AddMetadataField(in wstring strField, in wstring strDataType, in PRBool bWillRunLater);
  PRBool DeleteMetadataField(in wstring strField, in PRBool bWillRunLater);
  
  PRBool SetValueByIndex(in PRInt32 mediaIndex, in wstring strField, in wstring strValue, in PRBool bWillRunLater);
  
  PRBool SetValuesByIndex(in PRInt32 mediaIndex, in PRUint32 nMetaKeyCount, [array, size_is(nMetaKeyCount)] in wstring aMetaKeys, 
    in PRUint32 nMetadataValueCount, [array, size_is(nMetadataValueCount)] in wstring aMetaValues, in PRBool bWillRunLater);

  wstring GetValueByIndex(in PRInt32 mediaIndex, in wstring strField);
  
  void GetValuesByIndex(in PRInt32 mediaIndex, in PRUint32 nMetaKeyCount, [array, size_is(nMetaKeyCount)] in wstring aMetaKeys, 
    out PRUint32 nMetadataValueCount, [array, size_is (nMetadataValueCount), retval] out wstring aMetadataValues);
  
  PRBool SetValueByGUID(in wstring mediaGUID, in wstring strField, in wstring strValue, in PRBool bWillRunLater);
  
  PRBool SetValuesByGUID(in wstring mediaGUID, in PRUint32 nMetaKeyCount, [array, size_is(nMetaKeyCount)] in wstring aMetaKeys, 
    in PRUint32 nMetadataValueCount, [array, size_is(nMetadataValueCount)] in wstring aMetaValues, in PRBool bWillRunLater);

  wstring GetValueByGUID(in wstring mediaGUID, in wstring strField); 
  
  void GetValuesByGUID(in wstring mediaGUID, in PRUint32 nMetaKeyCount, [array, size_is (nMetaKeyCount)] in wstring aMetaKeys, 
    out PRUint32 nMetadataValueCount, [array, size_is (nMetadataValueCount), retval] out wstring aMetadataValues);
};

[scriptable, uuid(0F75EA33-A1FD-4bf6-8D13-DBAC96CAA668)]
interface sbIMediaScanCallback : nsISupports
{
  void OnMediaScanStart();
  void OnMediaScanFile(in wstring strFilePath, in PRInt32 nFileCount);
  void OnMediaScanEnd();
};

[scriptable, uuid(32CD5811-77BF-4800-A4A8-FE764B8DDFD1)]
interface sbIMediaScanQuery : nsISupports
{
  void SetDirectory(in wstring strDirectory);
  wstring GetDirectory();

  void SetRecurse(in PRBool bRecurse);
  PRBool GetRecurse();

  void SetCallback(in sbIMediaScanCallback pCallback);
  sbIMediaScanCallback GetCallback();

  PRUint32 GetFileCount();

  void AddFilePath(in wstring strFilePath);
  wstring GetFilePath(in PRUint32 nIndex);

  PRBool IsScanning();
  void SetIsScanning(in PRBool bIsScanning);

  wstring GetLastFileFound();

  wstring GetCurrentScanPath();
  void SetCurrentScanPath(in wstring strScanPath);
};

[scriptable, uuid(12BC75D3-8FD4-4b19-8F5B-CEF353E5168D)]
interface sbIMediaScan : nsISupports
{ 
  void SubmitQuery(in sbIMediaScanQuery pQuery);
  PRInt32 ScanDirectory(in wstring strDirectory, in PRBool bRecurse, in sbIMediaScanCallback pCallback);
};