/*
 //
// BEGIN SONGBIRD GPL
// 
// This file is part of the Songbird web player.
//
// Copyright© 2006 Pioneers of the Inevitable LLC
// http://songbirdnest.com
// 
// This file may be licensed under the terms of of the
// GNU General Public License Version 2 (the “GPL”).
// 
// Software distributed under the License is distributed 
// on an “AS IS” basis, WITHOUT WARRANTY OF ANY KIND, either 
// express or implied. See the GPL for the specific language 
// governing rights and limitations.
//
// You should have received a copy of the GPL along with this 
// program. If not, go to http://www.gnu.org/licenses/gpl.html
// or write to the Free Software Foundation, Inc., 
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
// 
// END SONGBIRD GPL
//
 */

#include "nsISupports.idl"
#include "IPlaylist.idl"

[scriptable, uuid(5D32F88B-D83F-42f9-BF6E-D56E833A78BA)]
interface sbIPlaylistPlayback : nsISupports
{
  const PRUint32 REPEAT_OFF = 0;
  const PRUint32 REPEAT_ALL = 1;
  const PRUint32 REPEAT_ONE = 2;

  PRBool Play(in wstring dbGUID, in wstring strTable, in PRInt32 nStartPos);
  PRBool PlayObject(in sbIPlaylist playlistObj, in PRInt32 nStartPos);
  
  PRBool Pause();
  PRBool Stop();

  PRInt32 Next();
  PRInt32 Previous();
  PRInt32 Current();

  PRBool AddItem(in wstring dbGUID, in wstring mediaGUID);
  PRInt32 GetItemCount();
  PRInt32 RemoveItem(in PRInt32 itemIndex);

  PRInt32 GetVolume();
  PRBool SetVolume(in PRInt32 vol);

  PRBool GetMute();
  void SetMute(in PRBool mute);

  PRInt64 GetLength();

  PRInt64 GetPosition();
  PRBool SetPosition(in PRInt64 pos);

  wstring CurrentGUID();
  wstring CurrentURL();

  void SetRepeat(in PRInt32 repeatMode);
  PRInt32 GetRepeat(); 

  PRBool GetShuffle();
  void SetShuffle(in PRBool bShuffle); 

  /*Metadata Get/Set*/
  void GetMetadataFields(out PRUint32 nMetadataFieldCount, [array, size_is(nMetadataFieldCount), retval] out wstring aMetaFields);
  
  wstring GetCurrentValue(in wstring strField);
  void GetCurrentValues(in PRUint32 nMetadataFieldCount, [array, size_is(nMetadataFieldCount)] in wstring aMetaFields,
    out PRUint32 nMetadataValueCount, [array, size_is(nMetadataValueCount), retval] out wstring aMetaValues);
  
  void SetCurrentValue(in wstring strField, in wstring strValue);
  void SetCurrentValues(in PRUint32 nMetadataFieldCount, [array, size_is(nMetadataFieldCount)] in wstring aMetaFields, 
    in PRUint32 nMetadataValueCount, [array, size_is(nMetadataValueCount)] in wstring aMetaValues);
};
