/*
 //
// BEGIN SONGBIRD GPL
// 
// This file is part of the Songbird web player.
//
// Copyright© 2006 POTI, Inc.
// http://songbirdnest.com
// 
// This file may be licensed under the terms of of the
// GNU General Public License Version 2 (the “GPL”).
// 
// Software distributed under the License is distributed 
// on an “AS IS” basis, WITHOUT WARRANTY OF ANY KIND, either 
// express or implied. See the GPL for the specific language 
// governing rights and limitations.
//
// You should have received a copy of the GPL along with this 
// program. If not, go to http://www.gnu.org/licenses/gpl.html
// or write to the Free Software Foundation, Inc., 
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
// 
// END SONGBIRD GPL
//
 */
/**
 * \file sbIDatabaseResult.idl
 * \brief 
 * 
 * \sa sbIDatabaseQuery.idl
 */
#include "nsISupports.idl"

/**
 * \interface sbIDatabaseResult
 * \brief
 *
 * \sa sbIDatabaseQuery
 */
[scriptable, uuid(D711447E-B6B0-4e63-A50E-3523794E08DF)]
interface sbIDatabaseResult : nsISupports
{
  /**
   * \brief 
   *
   * \param 
   * \sa sbIDatabaseQuery
   */
  PRInt32 getColumnCount();

  /**
   * \brief 
   *
   * \param 
   * \sa sbIDatabaseQuery
   */
  AString getColumnName(in PRInt32 dbColumn);

  /**
   * \brief 
   *
   * \param 
   * \sa sbIDatabaseQuery
   */
  PRInt32 getRowCount();

  /**
   * \brief 
   *
   * \param 
   * \sa sbIDatabaseQuery
   */
  AString getRowCell(in PRInt32 dbRow, in PRInt32 dbCell);

  /**
   * \brief 
   *
   * \param 
   * \sa sbIDatabaseQuery
   */
  AString getRowCellByColumn(in PRInt32 dbRow, in AString dbColumn);

  /**
   * \brief 
   *
   * \param 
   * \sa sbIDatabaseQuery
   */
  [noscript] wstring getColumnNamePtr(in PRInt32 dbColumn);

  /**
   * \brief 
   *
   * \param 
   * \sa sbIDatabaseQuery
   */
  [noscript] wstring getRowCellPtr(in PRInt32 dbRow, in PRInt32 dbCell);

  /**
   * \brief 
   *
   * \param 
   * \sa sbIDatabaseQuery
   */
  [noscript] wstring getRowCellByColumnPtr(in PRInt32 dbRow, in AString dbColumn);

  /**
   * \brief 
   *
   * \param 
   * \sa sbIDatabaseQuery
   */
  [noscript] void clearResultSet();
};