/*
//
// BEGIN SONGBIRD GPL
// 
// This file is part of the Songbird web player.
//
// Copyright(c) 2005-2007 POTI, Inc.
// http://songbirdnest.com
// 
// This file may be licensed under the terms of of the
// GNU General Public License Version 2 (the "GPL").
// 
// Software distributed under the License is distributed 
// on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either 
// express or implied. See the GPL for the specific language 
// governing rights and limitations.
//
// You should have received a copy of the GPL along with this 
// program. If not, go to http://www.gnu.org/licenses/gpl.html
// or write to the Free Software Foundation, Inc., 
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
// 
// END SONGBIRD GPL
//
 */

/**
 * \file sbIRemoteWebPlaylist.idl
 * \brief Definition of the Remote API WebPlaylist Interface
 */

#include "nsISupports.idl"

interface nsISimpleEnumerator;
interface sbIMediaListView;
interface sbIRemoteMediaList;

/*
Class: WebPlaylist

The <WebPlaylist> UI object. This object controls the UI that appears at
the bottom of the page. The information accessible here and operations
available here correspond to the the actual UI. Selection, column modification
and setting of the <MediaList> that serves as the data for the UI.

Columns:
A note about columns. All the columns in the UI are driven by the existance
of global level properties in Songbird. There are a number of types available
to the developer ( see addColumn() ). Each column must have a unique name and
there are a number system default names we use to get the default set of
columns. They are set when Songbird starts. When a column name is required as a
parameter to a function the default names can be used provided the operation
is not trying to add a column of that name. They can be passed in for the
before column, or they can be hidden via hideColumn().

The default columns have names of this format -
(begin code)
 http://songbirdnest.com/data/1.0#<columnIdentifier>
(end)

The complete list of column names can be found in 
http://publicsvn.songbirdnest.com/browser/trunk/components/property/src/sbStandardProperties.h

*/
/**
 * \interface sbIRemoteWebPlaylist
 * \brief An interface to control a media list from remote web pages.
 *
 * TODO: Write this documentation
 *
 */
[scriptable, uuid(6aa00573-1aaa-4ff9-9080-fbd172669997)]
interface sbIRemoteWebPlaylist : nsISupports
{
  /*
  Prop: mediaList

  The <MediaList> associated with this <WebPlaylist> instance.

  Type:
    <MediaList>
  */
  attribute sbIRemoteMediaList mediaList;

  /*
  Prop: selection

  The current selection in the <WebPlaylist>.

  Type:
    Enumerator, contains <MediaItems>.

  Example:
    (start code)
    //Get the current webplaylist.
    var webPlaylist = songbird.webPlaylist;
    

    //Get the currently selected mediaitems in the webplaylist.
    var selectedMediaItems = webPlaylist.selection;

    //Go through all the selected mediaitems.
    while(selectedMediaItems.hasMoreElements()) {
      var mediaItem = selectedMediaItems.getNext();

      //Do something with the mediaitem.
      ...
    }
    (end)

  See Also:
    Visit <http://www.xulplanet.com/references/xpcomref/ifaces/nsISimpleEnumerator.html> for nsISimpleEnumerator interface reference.
  */
  readonly attribute nsISimpleEnumerator selection;

  /*
  Func: setSelectionByIndex()

  Set the selection in the <WebPlaylist>.

  Prototype:
    setSelectionByIndex(Number index, Boolean selected)

  Parameters:
    index - Index of the item in the <WebPlaylist>. Index starts at 0.
    selected - Flag used for setting the selection state, may be true or false.

  Example:
    (start code)
    //Get the current webPlaylist.
    var webPlaylist = songbird.webPlaylist;

    //Select the first item.
    webPlaylist.setSelectionByIndex(0, true);

    //Select the third item.
    webPlaylist.setSelectionByIndex(2, true);

    //Unselect the first item.
    webPlaylist.setSelectionByIndex(0, false);
    (end)
  */
  void setSelectionByIndex(in unsigned long aIndex, in boolean aSelected);

  /*
  Func: addColumn()

  Add a column of data to the <WebPlaylist>. If the column already exists in
  the system and the hidden is false then the column will be shown before the
  column name passed in but no other settings will be adjusted.

  If you want to set the values of new columns for each track you must add
  the column before calling setProperty on each track. Otherwise the system
  will automatically add the property to the system as type text and it
  won't have the setting you set through this call.

  Prototype:
    addColumn(String columnType, 
              String columnName,  
              String displayName, 
              String buttonLabel, 
              String beforeColumn, 
              Boolean hidden, 
              Boolean viewable, 
              Boolean editable,
              Number nullSort,
              Number width)

  Parameters:
    columnType - The type of column.
    columnName - The name of the column.
    displayName - The displayed name of the column.
    buttonLabel - The label for a button, if of type simple/download button
    beforeColumn - Insert the new column before the column with this name. 
                   If an empty string is specified, the column is appended 
                   to the end of the existing columns.
    hidden - Hidden column by default.
    viewable - Column can be viewed by the user.
    editable - Column row cell values can be edited by the user.
    nullsort - The type of null sorting desired.
    width - The default width of the column when displayed.

  Column Types:
    text - Plain text.
    datetime - A time interval.
    uri - A URI (web address).
    number - A number.
    button - A clickable button.
    image - A picture.
    downloadbutton - A button which, when clicked, initiates a download.
    rating - 5 stars representing the value

  Null Sorting Types:
    0 - Null values are infinitely small.  This is the default.
    1 - Null values are infinitely large.
    2 - Null values are always first (regardless of sort direction)
    3 - Null values are always last

  Example:
    (start code)
    // add a text column to the web playlist
    songbird.webPlaylist.addColumn( "text",
                                    "http://domain.com/colname1",  // make sure it's unique
                                    "column heading goes here",
                                    "", // nothing needed for type text
                                    "", // add at the end
                                    false, // not hidden
                                    true, // can be viewed
                                    false, // read-only
                                    0,
                                    150); // pixels
    (end)

  See Also:
    <showColumnBefore()>
  */
  void addColumn( in AString aColumnType,
                  in AString aColumnName,
                  in AString aDisplayName,
                  in AString aButtonLabel,
                  in AString aBeforeColumnName,
                  in boolean aHidden,
                  in boolean aUserViewable,
                  in boolean aUserEditable,
                  in unsigned long aNullSort,
                  in unsigned long aWidth );

  /*
  Func: showColumnBefore()

  Show a column before another column. This enables you to move
  columns around visually as well as specify where you might want your own
  column to be shown.

  Prototype:
    showColumnBefore(String columnName, String beforeColumn)

  Parameters:
    columnName - The name of column to move.
    beforeColumn - Show the column with columnName 
                   before the column with beforeColumn.

  Example:
    (start code)
    (end)

  See Also:
    <addColumn()>
  */
  void showColumnBefore( in AString aColumnName,
                         in AString aBeforeColumnName );
};

