/*
//
// BEGIN SONGBIRD GPL
// 
// This file is part of the Songbird web player.
//
// Copyright(c) 2005-2007 POTI, Inc.
// http://songbirdnest.com
// 
// This file may be licensed under the terms of of the
// GNU General Public License Version 2 (the "GPL").
// 
// Software distributed under the License is distributed 
// on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either 
// express or implied. See the GPL for the specific language 
// governing rights and limitations.
//
// You should have received a copy of the GPL along with this 
// program. If not, go to http://www.gnu.org/licenses/gpl.html
// or write to the Free Software Foundation, Inc., 
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
// 
// END SONGBIRD GPL
//
 */

/**
 * \file sbIRemotePlayer.idl
 * \brief Definition of the Remote API Interfaces
 */

#include "nsISupports.idl"

interface nsIObserver;
interface sbIMediaListView;
interface sbIRemoteCommands;
interface sbIRemoteLibrary;
interface sbIRemoteMediaList;

/**
 * \interface sbIRemotePlayer
 *
 * This interface is a composition of many of our other interfaces with the
 *  goal of exposing a more web-friendly interface to web sites. The defines
 *  our "Remote API" the websites can call to get information about and interact
 *  with Sonbird.
 */
[scriptable, uuid(40964944-5243-4a16-886b-14c1cbaa79d9)]
interface sbIRemotePlayer : nsISupports
{
  /**
   * \brief The name of the player
   */
  readonly attribute AString name;

  /**
   * \brief The current web playlist
   */
  attribute sbIRemoteMediaList webPlaylist;

  /**
   * \brief The name of the artist for the currently playing track
   */
  readonly attribute AString currentArtist;

  /**
   * \brief The name of the album for the currently playing track
   */
  readonly attribute AString currentAlbum;

  /**
   * \brief The name of the currently playing track
   */
  readonly attribute AString currentTrack;

  /**
   * \brief Bind an observer to get called on changes to Songbird metadata/state
   */
  void addListener( in AString aKey,
                    in nsIObserver aObserver );

  /**
   * \brief Remove an observer from the metadata key
   */
  void removeListener( in AString aKey,
                       in nsIObserver aObserver );

  /**
   * \brief Being playback at the current location
   */
  void play();

  /**
   * \brief Play an media file by URL
   */
  void playURL(in AString aURL);

  /**
   * \brief Stop playback. Sets position to beginning.
   */
  void stop();

  /**
   * \brief Stop playback, leaves position at current location.
   */
  void pause();

  /**
   * \brief Skip to the next track and begin playing
   */
  void next();

  /**
   * \brief Skip to the previous track and begin playing
   */
  void previous();

  //
  // Commands
  //

  /**
   * \brief The collection of commands associated with the current page.
   */
  readonly attribute sbIRemoteCommands commands;

  //
  // Library creation and retrieval
  //

  // access to a sitelibrary for the given path
  sbIRemoteLibrary siteLibrary(in AString aDomain, in AString aPath);

  // access to any library in the system via path or 'magic' keyword
  sbIRemoteLibrary libraries(in AString aLibraryID);

  /**
   * \brief Fires the event to the webpage
   */
  [noscript] void fireEventToContent(in AString aClass, in AString aType);
  [noscript] void onCommandsChanged();

};



